package gui

// View is a user-defined view. Views are never displayed directly; a
// Layout is generated from the View. GenerateLayout returns the node's
// complete subtree — a view with children generates them itself, via
// appendChildViews.
//
// Pipeline: View -> generateViewLayout -> Layout ->
// layoutArrange -> renderLayout -> []RenderCmd
type View interface {
	GenerateLayout(w *Window) Layout
}

// ViewFunc adapts a function to a View, deferring construction to
// layout-generation time so the function can read window state. It is
// useful inside Content slices when a subtree needs State(*Window)
// but the enclosing function does not receive w.
type viewFunc func(*Window) View

// GenerateLayout calls the wrapped function and recursively
// builds the full Layout tree from the returned View.
func (f viewFunc) GenerateLayout(w *Window) Layout {
	v := f(w)
	if v == nil {
		return Layout{}
	}
	return generateViewLayout(v, w)
}

// ensureLayoutShape normalizes layout nodes so pipeline passes can
// safely dereference Shape fields.
func ensureLayoutShape(layout *Layout) {
	if layout == nil {
		return
	}
	if layout.Shape == nil {
		layout.Shape = &Shape{shapeType: shapeNone}
	}
}

// GenerateViewLayout builds the Layout tree for a View and normalizes
// the node's shape (ensureLayoutShape), so every pipeline pass can rely
// on a non-nil Shape.
//
// This is the supported entry point for composite View widgets. A
// widget package assembling a tree from child Views wants this one; a
// view that declares children uses appendChildViews to have the
// framework generate them.
func GenerateViewLayout(view View, w *Window) Layout {
	return generateViewLayout(view, w)
}

// generateViewLayout is the internal layout builder. The node's
// children — if it has any — were generated by its own
// GenerateLayout via appendChildViews; the only remaining invariant
// this function owns is shape normalization.
func generateViewLayout(view View, w *Window) Layout {
	layout := view.GenerateLayout(w)
	ensureLayoutShape(&layout)
	return layout
}

// appendChildViews generates children under parent's ID scope and
// appends them to parent.Children, after whatever the parent already
// put there.
//
// Ordering matters: the parent's own shape must be built before this is
// called, because the parent's ID resolves in the *enclosing* scope while
// its children resolve under it. Children the parent injected directly
// (addGroupBoxTitle's eraser + label) keep their position ahead of these.
func appendChildViews(w *Window, parent *Layout, children []View) {
	appendChildViewsScoped(w, parent, children, true)
}

// appendChildViewsFlat appends children WITHOUT pushing the parent's ID
// scope, so they resolve in the parent's enclosing scope.
//
// Exactly one caller: Form, and only to preserve today's observable
// effective IDs. Form's own field registry is NOT affected either way —
// FormFieldAdapterCfg.FieldID never passes through ID resolution. What
// scoping would change is the effective ID of every widget the caller
// put inside the form, and therefore SetFocus/FindByID against it.
//
// Form is therefore the one container whose children do not take its
// scope. That is deliberate here only in the sense that this refactor
// preserves it; whether it should hold at all is issue #306. This helper
// is the single place that decision would change.
func appendChildViewsFlat(w *Window, parent *Layout, children []View) {
	appendChildViewsScoped(w, parent, children, false)
}

func appendChildViewsScoped(
	w *Window, parent *Layout, children []View, scope bool,
) {
	// Callers build parent.Shape before calling: childScopeID reads its
	// ID to derive the child scope, and a shape built late (or a nil
	// shape — childScopeID's nil branch) silently generates the
	// children in the enclosing scope instead of under the parent.
	if len(children) == 0 {
		return
	}
	if len(children) > maxEventChildren {
		children = children[:maxEventChildren]
	}
	// Pre-size so append never reallocates; the reservation comes from the
	// frame-scoped arena (reset in resetViewPools) to avoid a per-node heap
	// allocation.
	wantCap := len(parent.Children) + len(children)
	if cap(parent.Children) < wantCap {
		var grown []Layout
		if w != nil {
			grown = w.scratch.takeLayoutChildren(wantCap)
		} else {
			grown = make([]Layout, 0, wantCap)
		}
		grown = grown[:len(parent.Children)]
		copy(grown, parent.Children)
		parent.Children = grown
	}
	// Saved and restored rather than recomputed on the way out: a sibling
	// must not inherit a child's scope.
	saved := ""
	pushed := scope && w != nil
	if pushed {
		saved = w.viewState.idScope
		w.viewState.idScope = childScopeID(w, saved, parent.Shape)
	}
	for _, child := range children {
		if child == nil {
			continue
		}
		parent.Children = append(
			parent.Children,
			generateViewLayout(child, w),
		)
	}
	if pushed {
		w.viewState.idScope = saved
	}
}
