package gui

// View is a user-defined view. Views are never displayed directly; a
// Layout is generated from the View. GenerateLayout returns the node's
// complete subtree — a view with children generates them itself, via
// appendChildViews.
//
// Pipeline: View -> generateViewLayout -> Layout ->
// layoutArrange -> renderLayout -> []RenderCmd
type View interface {
	GenerateLayout(w *Window) Layout
}

// ViewFunc adapts a function to a View, deferring construction to
// layout-generation time so the function can read window state. It is
// useful inside Content slices when a subtree needs State(*Window)
// but the enclosing function does not receive w.
type viewFunc func(*Window) View

// GenerateLayout calls the wrapped function and recursively
// builds the full Layout tree from the returned View.
func (f viewFunc) GenerateLayout(w *Window) Layout {
	v := f(w)
	if v == nil {
		return Layout{}
	}
	return generateViewLayout(v, w)
}

// ensureLayoutShape normalizes layout nodes so pipeline passes can
// safely dereference Shape fields.
func ensureLayoutShape(layout *Layout) {
	if layout == nil {
		return
	}
	if layout.Shape == nil {
		layout.Shape = &Shape{shapeType: shapeNone}
	}
}

// GenerateViewLayout builds the Layout tree for a View and normalizes
// the node's shape (ensureLayoutShape), so every pipeline pass can rely
// on a non-nil Shape.
//
// This is the supported entry point for composite View widgets. A
// widget package assembling a tree from child Views wants this one; a
// view that declares children uses appendChildViews to have the
// framework generate them.
func GenerateViewLayout(view View, w *Window) Layout {
	return generateViewLayout(view, w)
}

// generateViewLayout is the internal layout builder. The node's
// children — if it has any — were generated by its own
// GenerateLayout via appendChildViews; the only remaining invariant
// this function owns is shape normalization.
func generateViewLayout(view View, w *Window) Layout {
	layout := view.GenerateLayout(w)
	ensureLayoutShape(&layout)
	return layout
}

// appendChildViews generates children under parent's ID scope and
// appends them to parent.Children, after whatever the parent already
// put there.
//
// Ordering matters: the parent's own shape must be built before this is
// called, because the parent's ID resolves in the *enclosing* scope while
// its children resolve under it. Children the parent injected directly
// (addGroupBoxTitle's eraser + label) keep their position ahead of these.
func appendChildViews(w *Window, parent *Layout, children []View) {
	appendChildViewsScoped(w, parent, children, true)
}

func appendChildViewsScoped(
	w *Window, parent *Layout, children []View, scope bool,
) {
	// PRECONDITION: parent.Shape is non-nil. All three callers build it
	// before calling; childScopeID reads it immediately below, so a
	// normalization here would only move the nil deref one line down.
	if len(children) == 0 {
		return
	}
	if len(children) > maxEventChildren {
		children = children[:maxEventChildren]
	}
	// Pre-size so append never reallocates; the reservation comes from the
	// frame-scoped arena (reset in resetViewPools) to avoid a per-node heap
	// allocation.
	wantCap := len(parent.Children) + len(children)
	if cap(parent.Children) < wantCap {
		var grown []Layout
		if w != nil {
			grown = w.scratch.takeLayoutChildren(wantCap)
		} else {
			grown = make([]Layout, 0, wantCap)
		}
		grown = grown[:len(parent.Children)]
		copy(grown, parent.Children)
		parent.Children = grown
	}
	// Saved and restored rather than recomputed on the way out: a sibling
	// must not inherit a child's scope.
	saved := ""
	pushed := scope && w != nil
	if pushed {
		saved = w.viewState.idScope
		w.viewState.idScope = childScopeID(w, saved, parent.Shape)
	}
	for _, child := range children {
		if child == nil {
			continue
		}
		parent.Children = append(
			parent.Children,
			generateViewLayout(child, w),
		)
	}
	if pushed {
		w.viewState.idScope = saved
	}
}
