// Code generated by wlgen from cursor_shape_v1.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

func defineCursorShapeV1() {
	defineInterface(&WpCursorShapeManagerV1Interface, "wp_cursor_shape_manager_v1", 2,
		[]message{
			newMessage("destroy", "", nil),
			newMessage("get_pointer", "no", []*Interface{&WpCursorShapeDeviceV1Interface, &PointerInterface}),
			newMessage("get_tablet_tool_v2", "no", []*Interface{&WpCursorShapeDeviceV1Interface, nil}),
		},
		nil,
	)
	defineInterface(&WpCursorShapeDeviceV1Interface, "wp_cursor_shape_device_v1", 2,
		[]message{
			newMessage("destroy", "", nil),
			newMessage("set_shape", "uu", []*Interface{nil, nil}),
		},
		nil,
	)
}
