// Code generated by wlgen from fractional_scale_v1.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

func defineFractionalScaleV1() {
	defineInterface(&WpFractionalScaleManagerV1Interface, "wp_fractional_scale_manager_v1", 1,
		[]message{
			newMessage("destroy", "", nil),
			newMessage("get_fractional_scale", "no", []*Interface{&WpFractionalScaleV1Interface, &SurfaceInterface}),
		},
		nil,
	)
	defineInterface(&WpFractionalScaleV1Interface, "wp_fractional_scale_v1", 1,
		[]message{
			newMessage("destroy", "", nil),
		},
		[]message{
			newMessage("preferred_scale", "u", []*Interface{nil}),
		},
	)
}
