// Code generated by wlgen from input_method_unstable_v2.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

func defineInputMethodUnstableV2() {
	defineInterface(&ZwpInputMethodV2Interface, "zwp_input_method_v2", 1,
		[]message{
			newMessage("commit_string", "s", []*Interface{nil}),
			newMessage("set_preedit_string", "sii", []*Interface{nil, nil, nil}),
			newMessage("delete_surrounding_text", "uu", []*Interface{nil, nil}),
			newMessage("commit", "u", []*Interface{nil}),
			newMessage("get_input_popup_surface", "no", []*Interface{&ZwpInputPopupSurfaceV2Interface, &SurfaceInterface}),
			newMessage("grab_keyboard", "n", []*Interface{&ZwpInputMethodKeyboardGrabV2Interface}),
			newMessage("destroy", "", nil),
		},
		[]message{
			newMessage("activate", "", nil),
			newMessage("deactivate", "", nil),
			newMessage("surrounding_text", "suu", []*Interface{nil, nil, nil}),
			newMessage("text_change_cause", "u", []*Interface{nil}),
			newMessage("content_type", "uu", []*Interface{nil, nil}),
			newMessage("done", "", nil),
			newMessage("unavailable", "", nil),
		},
	)
	defineInterface(&ZwpInputPopupSurfaceV2Interface, "zwp_input_popup_surface_v2", 1,
		[]message{
			newMessage("destroy", "", nil),
		},
		[]message{
			newMessage("text_input_rectangle", "iiii", []*Interface{nil, nil, nil, nil}),
		},
	)
	defineInterface(&ZwpInputMethodKeyboardGrabV2Interface, "zwp_input_method_keyboard_grab_v2", 1,
		[]message{
			newMessage("release", "", nil),
		},
		[]message{
			newMessage("keymap", "uhu", []*Interface{nil, nil, nil}),
			newMessage("key", "uuuu", []*Interface{nil, nil, nil, nil}),
			newMessage("modifiers", "uuuuu", []*Interface{nil, nil, nil, nil, nil}),
			newMessage("repeat_info", "ii", []*Interface{nil, nil}),
		},
	)
	defineInterface(&ZwpInputMethodManagerV2Interface, "zwp_input_method_manager_v2", 1,
		[]message{
			newMessage("get_input_method", "on", []*Interface{&SeatInterface, &ZwpInputMethodV2Interface}),
			newMessage("destroy", "", nil),
		},
		nil,
	)
}
