// Code generated by wlgen from the protocol XML files. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

// defineInterfaces fills every generated wl_interface table. Load calls it once.
func defineInterfaces() {
	defineWayland()
	defineXdgShell()
}

// allInterfaces lists every generated table, for tests.
var allInterfaces = []*Interface{
	&DisplayInterface,
	&RegistryInterface,
	&CallbackInterface,
	&CompositorInterface,
	&ShmPoolInterface,
	&ShmInterface,
	&BufferInterface,
	&DataOfferInterface,
	&DataSourceInterface,
	&DataDeviceInterface,
	&DataDeviceManagerInterface,
	&ShellInterface,
	&ShellSurfaceInterface,
	&SurfaceInterface,
	&SeatInterface,
	&PointerInterface,
	&KeyboardInterface,
	&TouchInterface,
	&OutputInterface,
	&RegionInterface,
	&SubcompositorInterface,
	&SubsurfaceInterface,
	&XdgWmBaseInterface,
	&XdgPositionerInterface,
	&XdgSurfaceInterface,
	&XdgToplevelInterface,
	&XdgPopupInterface,
}
