// Code generated by wlgen from the protocol XML files. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

// defineInterfaces fills every generated wl_interface table. Load calls it once.
func defineInterfaces() {
	defineWayland()
	defineXdgShell()
	defineXdgDecorationUnstableV1()
	defineViewporter()
	defineFractionalScaleV1()
	defineCursorShapeV1()
	defineTextInputUnstableV3()
	defineWpPrimarySelectionUnstableV1()
	defineWlrVirtualPointerUnstableV1()
	defineInputMethodUnstableV2()
}

// allInterfaces lists every generated table, for tests.
var allInterfaces = []*Interface{
	&DisplayInterface,
	&RegistryInterface,
	&CallbackInterface,
	&CompositorInterface,
	&ShmPoolInterface,
	&ShmInterface,
	&BufferInterface,
	&DataOfferInterface,
	&DataSourceInterface,
	&DataDeviceInterface,
	&DataDeviceManagerInterface,
	&ShellInterface,
	&ShellSurfaceInterface,
	&SurfaceInterface,
	&SeatInterface,
	&PointerInterface,
	&KeyboardInterface,
	&TouchInterface,
	&OutputInterface,
	&RegionInterface,
	&SubcompositorInterface,
	&SubsurfaceInterface,
	&XdgWmBaseInterface,
	&XdgPositionerInterface,
	&XdgSurfaceInterface,
	&XdgToplevelInterface,
	&XdgPopupInterface,
	&ZxdgDecorationManagerV1Interface,
	&ZxdgToplevelDecorationV1Interface,
	&WpViewporterInterface,
	&WpViewportInterface,
	&WpFractionalScaleManagerV1Interface,
	&WpFractionalScaleV1Interface,
	&WpCursorShapeManagerV1Interface,
	&WpCursorShapeDeviceV1Interface,
	&ZwpTextInputV3Interface,
	&ZwpTextInputManagerV3Interface,
	&ZwpPrimarySelectionDeviceManagerV1Interface,
	&ZwpPrimarySelectionDeviceV1Interface,
	&ZwpPrimarySelectionOfferV1Interface,
	&ZwpPrimarySelectionSourceV1Interface,
	&ZwlrVirtualPointerV1Interface,
	&ZwlrVirtualPointerManagerV1Interface,
	&ZwpInputMethodV2Interface,
	&ZwpInputPopupSurfaceV2Interface,
	&ZwpInputMethodKeyboardGrabV2Interface,
	&ZwpInputMethodManagerV2Interface,
}
