// Code generated by wlgen from text_input_unstable_v3.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

func defineTextInputUnstableV3() {
	defineInterface(&ZwpTextInputV3Interface, "zwp_text_input_v3", 1,
		[]message{
			newMessage("destroy", "", nil),
			newMessage("enable", "", nil),
			newMessage("disable", "", nil),
			newMessage("set_surrounding_text", "sii", []*Interface{nil, nil, nil}),
			newMessage("set_text_change_cause", "u", []*Interface{nil}),
			newMessage("set_content_type", "uu", []*Interface{nil, nil}),
			newMessage("set_cursor_rectangle", "iiii", []*Interface{nil, nil, nil, nil}),
			newMessage("commit", "", nil),
		},
		[]message{
			newMessage("enter", "o", []*Interface{&SurfaceInterface}),
			newMessage("leave", "o", []*Interface{&SurfaceInterface}),
			newMessage("preedit_string", "?sii", []*Interface{nil, nil, nil}),
			newMessage("commit_string", "?s", []*Interface{nil}),
			newMessage("delete_surrounding_text", "uu", []*Interface{nil, nil}),
			newMessage("done", "u", []*Interface{nil}),
		},
	)
	defineInterface(&ZwpTextInputManagerV3Interface, "zwp_text_input_manager_v3", 1,
		[]message{
			newMessage("destroy", "", nil),
			newMessage("get_text_input", "no", []*Interface{&ZwpTextInputV3Interface, &SeatInterface}),
		},
		nil,
	)
}
