// Code generated by wlgen from viewporter.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

func defineViewporter() {
	defineInterface(&WpViewporterInterface, "wp_viewporter", 1,
		[]message{
			newMessage("destroy", "", nil),
			newMessage("get_viewport", "no", []*Interface{&WpViewportInterface, &SurfaceInterface}),
		},
		nil,
	)
	defineInterface(&WpViewportInterface, "wp_viewport", 1,
		[]message{
			newMessage("destroy", "", nil),
			newMessage("set_source", "ffff", []*Interface{nil, nil, nil, nil}),
			newMessage("set_destination", "ii", []*Interface{nil, nil}),
		},
		nil,
	)
}
