// Code generated by wlgen from wayland.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

func defineWayland() {
	defineInterface(&DisplayInterface, "wl_display", 1,
		[]message{
			newMessage("sync", "n", []*Interface{&CallbackInterface}),
			newMessage("get_registry", "n", []*Interface{&RegistryInterface}),
		},
		[]message{
			newMessage("error", "ous", []*Interface{nil, nil, nil}),
			newMessage("delete_id", "u", []*Interface{nil}),
		},
	)
	defineInterface(&RegistryInterface, "wl_registry", 1,
		[]message{
			newMessage("bind", "usun", []*Interface{nil, nil, nil, nil}),
		},
		[]message{
			newMessage("global", "usu", []*Interface{nil, nil, nil}),
			newMessage("global_remove", "u", []*Interface{nil}),
		},
	)
	defineInterface(&CallbackInterface, "wl_callback", 1,
		nil,
		[]message{
			newMessage("done", "u", []*Interface{nil}),
		},
	)
	defineInterface(&CompositorInterface, "wl_compositor", 6,
		[]message{
			newMessage("create_surface", "n", []*Interface{&SurfaceInterface}),
			newMessage("create_region", "n", []*Interface{&RegionInterface}),
		},
		nil,
	)
	defineInterface(&ShmPoolInterface, "wl_shm_pool", 2,
		[]message{
			newMessage("create_buffer", "niiiiu", []*Interface{&BufferInterface, nil, nil, nil, nil, nil}),
			newMessage("destroy", "", nil),
			newMessage("resize", "i", []*Interface{nil}),
		},
		nil,
	)
	defineInterface(&ShmInterface, "wl_shm", 2,
		[]message{
			newMessage("create_pool", "nhi", []*Interface{&ShmPoolInterface, nil, nil}),
			newMessage("release", "2", nil),
		},
		[]message{
			newMessage("format", "u", []*Interface{nil}),
		},
	)
	defineInterface(&BufferInterface, "wl_buffer", 1,
		[]message{
			newMessage("destroy", "", nil),
		},
		[]message{
			newMessage("release", "", nil),
		},
	)
	defineInterface(&DataOfferInterface, "wl_data_offer", 3,
		[]message{
			newMessage("accept", "u?s", []*Interface{nil, nil}),
			newMessage("receive", "sh", []*Interface{nil, nil}),
			newMessage("destroy", "", nil),
			newMessage("finish", "3", nil),
			newMessage("set_actions", "3uu", []*Interface{nil, nil}),
		},
		[]message{
			newMessage("offer", "s", []*Interface{nil}),
			newMessage("source_actions", "3u", []*Interface{nil}),
			newMessage("action", "3u", []*Interface{nil}),
		},
	)
	defineInterface(&DataSourceInterface, "wl_data_source", 3,
		[]message{
			newMessage("offer", "s", []*Interface{nil}),
			newMessage("destroy", "", nil),
			newMessage("set_actions", "3u", []*Interface{nil}),
		},
		[]message{
			newMessage("target", "?s", []*Interface{nil}),
			newMessage("send", "sh", []*Interface{nil, nil}),
			newMessage("cancelled", "", nil),
			newMessage("dnd_drop_performed", "3", nil),
			newMessage("dnd_finished", "3", nil),
			newMessage("action", "3u", []*Interface{nil}),
		},
	)
	defineInterface(&DataDeviceInterface, "wl_data_device", 3,
		[]message{
			newMessage("start_drag", "?oo?ou", []*Interface{&DataSourceInterface, &SurfaceInterface, &SurfaceInterface, nil}),
			newMessage("set_selection", "?ou", []*Interface{&DataSourceInterface, nil}),
			newMessage("release", "2", nil),
		},
		[]message{
			newMessage("data_offer", "n", []*Interface{&DataOfferInterface}),
			newMessage("enter", "uoff?o", []*Interface{nil, &SurfaceInterface, nil, nil, &DataOfferInterface}),
			newMessage("leave", "", nil),
			newMessage("motion", "uff", []*Interface{nil, nil, nil}),
			newMessage("drop", "", nil),
			newMessage("selection", "?o", []*Interface{&DataOfferInterface}),
		},
	)
	defineInterface(&DataDeviceManagerInterface, "wl_data_device_manager", 3,
		[]message{
			newMessage("create_data_source", "n", []*Interface{&DataSourceInterface}),
			newMessage("get_data_device", "no", []*Interface{&DataDeviceInterface, &SeatInterface}),
		},
		nil,
	)
	defineInterface(&ShellInterface, "wl_shell", 1,
		[]message{
			newMessage("get_shell_surface", "no", []*Interface{&ShellSurfaceInterface, &SurfaceInterface}),
		},
		nil,
	)
	defineInterface(&ShellSurfaceInterface, "wl_shell_surface", 1,
		[]message{
			newMessage("pong", "u", []*Interface{nil}),
			newMessage("move", "ou", []*Interface{&SeatInterface, nil}),
			newMessage("resize", "ouu", []*Interface{&SeatInterface, nil, nil}),
			newMessage("set_toplevel", "", nil),
			newMessage("set_transient", "oiiu", []*Interface{&SurfaceInterface, nil, nil, nil}),
			newMessage("set_fullscreen", "uu?o", []*Interface{nil, nil, &OutputInterface}),
			newMessage("set_popup", "ouoiiu", []*Interface{&SeatInterface, nil, &SurfaceInterface, nil, nil, nil}),
			newMessage("set_maximized", "?o", []*Interface{&OutputInterface}),
			newMessage("set_title", "s", []*Interface{nil}),
			newMessage("set_class", "s", []*Interface{nil}),
		},
		[]message{
			newMessage("ping", "u", []*Interface{nil}),
			newMessage("configure", "uii", []*Interface{nil, nil, nil}),
			newMessage("popup_done", "", nil),
		},
	)
	defineInterface(&SurfaceInterface, "wl_surface", 6,
		[]message{
			newMessage("destroy", "", nil),
			newMessage("attach", "?oii", []*Interface{&BufferInterface, nil, nil}),
			newMessage("damage", "iiii", []*Interface{nil, nil, nil, nil}),
			newMessage("frame", "n", []*Interface{&CallbackInterface}),
			newMessage("set_opaque_region", "?o", []*Interface{&RegionInterface}),
			newMessage("set_input_region", "?o", []*Interface{&RegionInterface}),
			newMessage("commit", "", nil),
			newMessage("set_buffer_transform", "2i", []*Interface{nil}),
			newMessage("set_buffer_scale", "3i", []*Interface{nil}),
			newMessage("damage_buffer", "4iiii", []*Interface{nil, nil, nil, nil}),
			newMessage("offset", "5ii", []*Interface{nil, nil}),
		},
		[]message{
			newMessage("enter", "o", []*Interface{&OutputInterface}),
			newMessage("leave", "o", []*Interface{&OutputInterface}),
			newMessage("preferred_buffer_scale", "6i", []*Interface{nil}),
			newMessage("preferred_buffer_transform", "6u", []*Interface{nil}),
		},
	)
	defineInterface(&SeatInterface, "wl_seat", 9,
		[]message{
			newMessage("get_pointer", "n", []*Interface{&PointerInterface}),
			newMessage("get_keyboard", "n", []*Interface{&KeyboardInterface}),
			newMessage("get_touch", "n", []*Interface{&TouchInterface}),
			newMessage("release", "5", nil),
		},
		[]message{
			newMessage("capabilities", "u", []*Interface{nil}),
			newMessage("name", "2s", []*Interface{nil}),
		},
	)
	defineInterface(&PointerInterface, "wl_pointer", 9,
		[]message{
			newMessage("set_cursor", "u?oii", []*Interface{nil, &SurfaceInterface, nil, nil}),
			newMessage("release", "3", nil),
		},
		[]message{
			newMessage("enter", "uoff", []*Interface{nil, &SurfaceInterface, nil, nil}),
			newMessage("leave", "uo", []*Interface{nil, &SurfaceInterface}),
			newMessage("motion", "uff", []*Interface{nil, nil, nil}),
			newMessage("button", "uuuu", []*Interface{nil, nil, nil, nil}),
			newMessage("axis", "uuf", []*Interface{nil, nil, nil}),
			newMessage("frame", "5", nil),
			newMessage("axis_source", "5u", []*Interface{nil}),
			newMessage("axis_stop", "5uu", []*Interface{nil, nil}),
			newMessage("axis_discrete", "5ui", []*Interface{nil, nil}),
			newMessage("axis_value120", "8ui", []*Interface{nil, nil}),
			newMessage("axis_relative_direction", "9uu", []*Interface{nil, nil}),
		},
	)
	defineInterface(&KeyboardInterface, "wl_keyboard", 9,
		[]message{
			newMessage("release", "3", nil),
		},
		[]message{
			newMessage("keymap", "uhu", []*Interface{nil, nil, nil}),
			newMessage("enter", "uoa", []*Interface{nil, &SurfaceInterface, nil}),
			newMessage("leave", "uo", []*Interface{nil, &SurfaceInterface}),
			newMessage("key", "uuuu", []*Interface{nil, nil, nil, nil}),
			newMessage("modifiers", "uuuuu", []*Interface{nil, nil, nil, nil, nil}),
			newMessage("repeat_info", "4ii", []*Interface{nil, nil}),
		},
	)
	defineInterface(&TouchInterface, "wl_touch", 9,
		[]message{
			newMessage("release", "3", nil),
		},
		[]message{
			newMessage("down", "uuoiff", []*Interface{nil, nil, &SurfaceInterface, nil, nil, nil}),
			newMessage("up", "uui", []*Interface{nil, nil, nil}),
			newMessage("motion", "uiff", []*Interface{nil, nil, nil, nil}),
			newMessage("frame", "", nil),
			newMessage("cancel", "", nil),
			newMessage("shape", "6iff", []*Interface{nil, nil, nil}),
			newMessage("orientation", "6if", []*Interface{nil, nil}),
		},
	)
	defineInterface(&OutputInterface, "wl_output", 4,
		[]message{
			newMessage("release", "3", nil),
		},
		[]message{
			newMessage("geometry", "iiiiissi", []*Interface{nil, nil, nil, nil, nil, nil, nil, nil}),
			newMessage("mode", "uiii", []*Interface{nil, nil, nil, nil}),
			newMessage("done", "2", nil),
			newMessage("scale", "2i", []*Interface{nil}),
			newMessage("name", "4s", []*Interface{nil}),
			newMessage("description", "4s", []*Interface{nil}),
		},
	)
	defineInterface(&RegionInterface, "wl_region", 1,
		[]message{
			newMessage("destroy", "", nil),
			newMessage("add", "iiii", []*Interface{nil, nil, nil, nil}),
			newMessage("subtract", "iiii", []*Interface{nil, nil, nil, nil}),
		},
		nil,
	)
	defineInterface(&SubcompositorInterface, "wl_subcompositor", 1,
		[]message{
			newMessage("destroy", "", nil),
			newMessage("get_subsurface", "noo", []*Interface{&SubsurfaceInterface, &SurfaceInterface, &SurfaceInterface}),
		},
		nil,
	)
	defineInterface(&SubsurfaceInterface, "wl_subsurface", 1,
		[]message{
			newMessage("destroy", "", nil),
			newMessage("set_position", "ii", []*Interface{nil, nil}),
			newMessage("place_above", "o", []*Interface{&SurfaceInterface}),
			newMessage("place_below", "o", []*Interface{&SurfaceInterface}),
			newMessage("set_sync", "", nil),
			newMessage("set_desync", "", nil),
		},
		nil,
	)
}
