// Code generated by wlgen from wayland.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// Buffer is wl_buffer: content for a wl_surface.
type Buffer struct{ Proxy }

// BufferInterface is the wl_interface table for wl_buffer.
var BufferInterface Interface

// Destroy sends wl_buffer.destroy: destroy a buffer.
// It destroys the proxy; do not use it afterwards.
func (px Buffer) Destroy() {
	px.marshal(0, nil, 0, marshalFlagDestroy)
}

// BufferHandlers holds one func per wl_buffer event. A nil func ignores the event.
// Strings and arrays are only valid until the func returns.
type BufferHandlers struct {
	// Release is wl_buffer.release: compositor releases buffer.
	Release func()
}

// SetHandlers routes the events of px to h, replacing any earlier handlers.
func (px Buffer) SetHandlers(h BufferHandlers) {
	px.setDispatch(func(opcode uint32, a *argSlots) {
		switch opcode {
		case 0:
			if h.Release != nil {
				h.Release()
			}
		}
	})
}
