// Code generated by wlgen from wayland.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// Callback is wl_callback: callback object.
type Callback struct{ Proxy }

// CallbackInterface is the wl_interface table for wl_callback.
var CallbackInterface Interface

// CallbackHandlers holds one func per wl_callback event. A nil func ignores the event.
// Strings and arrays are only valid until the func returns.
type CallbackHandlers struct {
	// Done is wl_callback.done: done event.
	Done func(callbackData uint32)
}

// SetHandlers routes the events of px to h, replacing any earlier handlers.
func (px Callback) SetHandlers(h CallbackHandlers) {
	px.setDispatch(func(opcode uint32, a *argSlots) {
		switch opcode {
		case 0:
			if h.Done != nil {
				h.Done(uint32(a[0]))
			}
		}
	})
}
