// Code generated by wlgen from wayland.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// Compositor is wl_compositor: the compositor singleton.
type Compositor struct{ Proxy }

// CompositorInterface is the wl_interface table for wl_compositor.
var CompositorInterface Interface

// CreateSurface sends wl_compositor.create_surface: create new surface.
func (px Compositor) CreateSurface() Surface {
	ver := px.Version()
	r := px.marshal(0, &SurfaceInterface, ver, 0, 0)
	return Surface{Proxy{ptr: r, ver: ver}}
}

// CreateRegion sends wl_compositor.create_region: create new region.
func (px Compositor) CreateRegion() Region {
	ver := px.Version()
	r := px.marshal(1, &RegionInterface, ver, 0, 0)
	return Region{Proxy{ptr: r, ver: ver}}
}
