// Code generated by wlgen from wayland.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// DataDeviceManager is wl_data_device_manager: data transfer interface.
type DataDeviceManager struct{ Proxy }

// DataDeviceManagerInterface is the wl_interface table for wl_data_device_manager.
var DataDeviceManagerInterface Interface

// DataDeviceManager.dnd_action enum.
const (
	// no action
	DataDeviceManagerDndActionNone = 0
	// copy action
	DataDeviceManagerDndActionCopy = 1
	// move action
	DataDeviceManagerDndActionMove = 2
	// ask action
	DataDeviceManagerDndActionAsk = 4
)

// CreateDataSource sends wl_data_device_manager.create_data_source: create a new data source.
func (px DataDeviceManager) CreateDataSource() DataSource {
	ver := px.Version()
	r := px.marshal(0, &DataSourceInterface, ver, 0, 0)
	return DataSource{Proxy{ptr: r, ver: ver}}
}

// GetDataDevice sends wl_data_device_manager.get_data_device: create a new data device.
func (px DataDeviceManager) GetDataDevice(seat Seat) DataDevice {
	ver := px.Version()
	r := px.marshal(1, &DataDeviceInterface, ver, 0, 0, seat.ptr)
	return DataDevice{Proxy{ptr: r, ver: ver}}
}
