// Code generated by wlgen from wayland.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// DataDevice is wl_data_device: data transfer device.
type DataDevice struct{ Proxy }

// DataDeviceInterface is the wl_interface table for wl_data_device.
var DataDeviceInterface Interface

// DataDevice.error enum.
const (
	// given wl_surface has another role
	DataDeviceErrorRole = 0
	// source has already been used
	DataDeviceErrorUsedSource = 1
)

// StartDrag sends wl_data_device.start_drag: start drag-and-drop operation.
func (px DataDevice) StartDrag(source DataSource, origin Surface, icon Surface, serial uint32) {
	px.marshal(0, nil, 0, 0, source.ptr, origin.ptr, icon.ptr, uintptr(serial))
}

// SetSelection sends wl_data_device.set_selection: copy data to the selection.
func (px DataDevice) SetSelection(source DataSource, serial uint32) {
	px.marshal(1, nil, 0, 0, source.ptr, uintptr(serial))
}

// Release sends wl_data_device.release: destroy data device.
// Needs version 2 of the bound object.
// It destroys the proxy; do not use it afterwards.
func (px DataDevice) Release() {
	px.marshal(2, nil, 0, marshalFlagDestroy)
}

// DataDeviceHandlers holds one func per wl_data_device event. A nil func ignores the event.
// Strings and arrays are only valid until the func returns.
type DataDeviceHandlers struct {
	// DataOffer is wl_data_device.data_offer: introduce a new wl_data_offer.
	DataOffer func(id DataOffer)
	// Enter is wl_data_device.enter: initiate drag-and-drop session.
	Enter func(serial uint32, surface Surface, x Fixed, y Fixed, id DataOffer)
	// Leave is wl_data_device.leave: end drag-and-drop session.
	Leave func()
	// Motion is wl_data_device.motion: drag-and-drop session motion.
	Motion func(time uint32, x Fixed, y Fixed)
	// Drop is wl_data_device.drop: end drag-and-drop session successfully.
	Drop func()
	// Selection is wl_data_device.selection: advertise new selection.
	Selection func(id DataOffer)
}

// SetHandlers routes the events of px to h, replacing any earlier handlers.
func (px DataDevice) SetHandlers(h DataDeviceHandlers) { px.SetDispatcher(h.Dispatcher()) }

// DataDeviceDispatcher is the decoder for DataDeviceHandlers, built once by Dispatcher
// and installed on any number of proxies without allocating.
type DataDeviceDispatcher struct {
	f func(opcode uint32, a *argSlots)
}

// SetDispatcher routes the events of px to d, replacing any earlier handlers.
func (px DataDevice) SetDispatcher(d DataDeviceDispatcher) { px.setDispatch(d.f) }

// Dispatcher builds the event decoder for h.
func (h DataDeviceHandlers) Dispatcher() DataDeviceDispatcher {
	return DataDeviceDispatcher{func(opcode uint32, a *argSlots) {
		switch opcode {
		case 0:
			if h.DataOffer != nil {
				h.DataOffer(DataOffer{Proxy{ptr: a[0]}})
			}
		case 1:
			if h.Enter != nil {
				h.Enter(uint32(a[0]), Surface{Proxy{ptr: a[1]}}, Fixed(int32(uint32(a[2]))), Fixed(int32(uint32(a[3]))), DataOffer{Proxy{ptr: a[4]}})
			}
		case 2:
			if h.Leave != nil {
				h.Leave()
			}
		case 3:
			if h.Motion != nil {
				h.Motion(uint32(a[0]), Fixed(int32(uint32(a[1]))), Fixed(int32(uint32(a[2]))))
			}
		case 4:
			if h.Drop != nil {
				h.Drop()
			}
		case 5:
			if h.Selection != nil {
				h.Selection(DataOffer{Proxy{ptr: a[0]}})
			}
		}
	}}
}
