// Code generated by wlgen from wayland.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// Display is wl_display: core global object.
type Display struct{ Proxy }

// DisplayInterface is the wl_interface table for wl_display.
var DisplayInterface Interface

// Display.error enum.
const (
	// server couldn't find object
	DisplayErrorInvalidObject = 0
	// method doesn't exist on the specified interface or malformed request
	DisplayErrorInvalidMethod = 1
	// server is out of memory
	DisplayErrorNoMemory = 2
	// implementation error in compositor
	DisplayErrorImplementation = 3
)

// Sync sends wl_display.sync: asynchronous roundtrip.
func (px Display) Sync() Callback {
	ver := px.Version()
	r := px.marshal(0, &CallbackInterface, ver, 0, 0)
	return Callback{Proxy{ptr: r, ver: ver}}
}

// GetRegistry sends wl_display.get_registry: get global registry object.
func (px Display) GetRegistry() Registry {
	ver := px.Version()
	r := px.marshal(1, &RegistryInterface, ver, 0, 0)
	return Registry{Proxy{ptr: r, ver: ver}}
}
