// Code generated by wlgen from wayland.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// DataOffer is wl_data_offer: offer to transfer data.
type DataOffer struct{ Proxy }

// DataOfferInterface is the wl_interface table for wl_data_offer.
var DataOfferInterface Interface

// DataOffer.error enum.
const (
	// finish request was called untimely
	DataOfferErrorInvalidFinish = 0
	// action mask contains invalid values
	DataOfferErrorInvalidActionMask = 1
	// action argument has an invalid value
	DataOfferErrorInvalidAction = 2
	// offer doesn't accept this request
	DataOfferErrorInvalidOffer = 3
)

// Accept sends wl_data_offer.accept: accept one of the offered mime types.
func (px DataOffer) Accept(serial uint32, mimeType string) {
	mimeTypeC := cString(mimeType, true)
	px.marshal(0, nil, 0, 0, uintptr(serial), cStringPtr(mimeTypeC))
	runtime.KeepAlive(mimeTypeC)
}

// Receive sends wl_data_offer.receive: request that the data is transferred.
func (px DataOffer) Receive(mimeType string, fd int) {
	mimeTypeC := cString(mimeType, false)
	px.marshal(1, nil, 0, 0, cStringPtr(mimeTypeC), uintptr(fd))
	runtime.KeepAlive(mimeTypeC)
}

// Destroy sends wl_data_offer.destroy: destroy data offer.
// It destroys the proxy; do not use it afterwards.
func (px DataOffer) Destroy() {
	px.marshal(2, nil, 0, marshalFlagDestroy)
}

// Finish sends wl_data_offer.finish: the offer will no longer be used.
// Needs version 3 of the bound object.
func (px DataOffer) Finish() {
	px.marshal(3, nil, 0, 0)
}

// SetActions sends wl_data_offer.set_actions: set the available/preferred drag-and-drop actions.
// Needs version 3 of the bound object.
func (px DataOffer) SetActions(dndActions uint32, preferredAction uint32) {
	px.marshal(4, nil, 0, 0, uintptr(dndActions), uintptr(preferredAction))
}

// DataOfferHandlers holds one func per wl_data_offer event. A nil func ignores the event.
// Strings and arrays are only valid until the func returns.
type DataOfferHandlers struct {
	// Offer is wl_data_offer.offer: advertise offered mime type.
	Offer func(mimeType string)
	// SourceActions is wl_data_offer.source_actions: notify the source-side available actions.
	SourceActions func(sourceActions uint32)
	// Action is wl_data_offer.action: notify the selected action.
	Action func(dndAction uint32)
}

// SetHandlers routes the events of px to h, replacing any earlier handlers.
func (px DataOffer) SetHandlers(h DataOfferHandlers) { px.SetDispatcher(h.Dispatcher()) }

// DataOfferDispatcher is the decoder for DataOfferHandlers, built once by Dispatcher
// and installed on any number of proxies without allocating.
type DataOfferDispatcher struct {
	f func(opcode uint32, a *argSlots)
}

// SetDispatcher routes the events of px to d, replacing any earlier handlers.
func (px DataOffer) SetDispatcher(d DataOfferDispatcher) { px.setDispatch(d.f) }

// Dispatcher builds the event decoder for h.
func (h DataOfferHandlers) Dispatcher() DataOfferDispatcher {
	return DataOfferDispatcher{func(opcode uint32, a *argSlots) {
		switch opcode {
		case 0:
			if h.Offer != nil {
				h.Offer(goString(a[0]))
			}
		case 1:
			if h.SourceActions != nil {
				h.SourceActions(uint32(a[0]))
			}
		case 2:
			if h.Action != nil {
				h.Action(uint32(a[0]))
			}
		}
	}}
}
