// Code generated by wlgen from wayland.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// DataSource is wl_data_source: offer to transfer data.
type DataSource struct{ Proxy }

// DataSourceInterface is the wl_interface table for wl_data_source.
var DataSourceInterface Interface

// DataSource.error enum.
const (
	// action mask contains invalid values
	DataSourceErrorInvalidActionMask = 0
	// source doesn't accept this request
	DataSourceErrorInvalidSource = 1
)

// Offer sends wl_data_source.offer: add an offered mime type.
func (px DataSource) Offer(mimeType string) {
	mimeTypeC := cString(mimeType, false)
	px.marshal(0, nil, 0, 0, cStringPtr(mimeTypeC))
	runtime.KeepAlive(mimeTypeC)
}

// Destroy sends wl_data_source.destroy: destroy the data source.
// It destroys the proxy; do not use it afterwards.
func (px DataSource) Destroy() {
	px.marshal(1, nil, 0, marshalFlagDestroy)
}

// SetActions sends wl_data_source.set_actions: set the available drag-and-drop actions.
// Needs version 3 of the bound object.
func (px DataSource) SetActions(dndActions uint32) {
	px.marshal(2, nil, 0, 0, uintptr(dndActions))
}

// DataSourceHandlers holds one func per wl_data_source event. A nil func ignores the event.
// Strings and arrays are only valid until the func returns.
type DataSourceHandlers struct {
	// Target is wl_data_source.target: a target accepts an offered mime type.
	Target func(mimeType string)
	// Send is wl_data_source.send: send the data.
	Send func(mimeType string, fd int)
	// Cancelled is wl_data_source.cancelled: selection was cancelled.
	Cancelled func()
	// DndDropPerformed is wl_data_source.dnd_drop_performed: the drag-and-drop operation physically finished.
	DndDropPerformed func()
	// DndFinished is wl_data_source.dnd_finished: the drag-and-drop operation concluded.
	DndFinished func()
	// Action is wl_data_source.action: notify the selected action.
	Action func(dndAction uint32)
}

// SetHandlers routes the events of px to h, replacing any earlier handlers.
func (px DataSource) SetHandlers(h DataSourceHandlers) {
	px.setDispatch(func(opcode uint32, a *argSlots) {
		switch opcode {
		case 0:
			if h.Target != nil {
				h.Target(goString(a[0]))
			}
		case 1:
			if h.Send != nil {
				h.Send(goString(a[0]), int(int32(uint32(a[1]))))
			}
		case 2:
			if h.Cancelled != nil {
				h.Cancelled()
			}
		case 3:
			if h.DndDropPerformed != nil {
				h.DndDropPerformed()
			}
		case 4:
			if h.DndFinished != nil {
				h.DndFinished()
			}
		case 5:
			if h.Action != nil {
				h.Action(uint32(a[0]))
			}
		}
	})
}
