// Code generated by wlgen from wayland.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// Keyboard is wl_keyboard: keyboard input device.
type Keyboard struct{ Proxy }

// KeyboardInterface is the wl_interface table for wl_keyboard.
var KeyboardInterface Interface

// Keyboard.keymap_format enum.
const (
	// no keymap; client must understand how to interpret the raw keycode
	KeyboardKeymapFormatNoKeymap = 0
	// libxkbcommon compatible, null-terminated string; to determine the xkb keycode, clients must add 8 to the key event keycode
	KeyboardKeymapFormatXkbV1 = 1
)

// Keyboard.key_state enum.
const (
	// key is not pressed
	KeyboardKeyStateReleased = 0
	// key is pressed
	KeyboardKeyStatePressed = 1
)

// Release sends wl_keyboard.release: release the keyboard object.
// Needs version 3 of the bound object.
// It destroys the proxy; do not use it afterwards.
func (px Keyboard) Release() {
	px.marshal(0, nil, 0, marshalFlagDestroy)
}

// KeyboardHandlers holds one func per wl_keyboard event. A nil func ignores the event.
// Strings and arrays are only valid until the func returns.
type KeyboardHandlers struct {
	// Keymap is wl_keyboard.keymap: keyboard mapping.
	Keymap func(format uint32, fd int, size uint32)
	// Enter is wl_keyboard.enter: enter event.
	Enter func(serial uint32, surface Surface, keys []byte)
	// Leave is wl_keyboard.leave: leave event.
	Leave func(serial uint32, surface Surface)
	// Key is wl_keyboard.key: key event.
	Key func(serial uint32, time uint32, key uint32, state uint32)
	// Modifiers is wl_keyboard.modifiers: modifier and group state.
	Modifiers func(serial uint32, modsDepressed uint32, modsLatched uint32, modsLocked uint32, group uint32)
	// RepeatInfo is wl_keyboard.repeat_info: repeat rate and delay.
	RepeatInfo func(rate int32, delay int32)
}

// SetHandlers routes the events of px to h, replacing any earlier handlers.
func (px Keyboard) SetHandlers(h KeyboardHandlers) {
	px.setDispatch(func(opcode uint32, a *argSlots) {
		switch opcode {
		case 0:
			if h.Keymap != nil {
				h.Keymap(uint32(a[0]), int(int32(uint32(a[1]))), uint32(a[2]))
			}
		case 1:
			if h.Enter != nil {
				h.Enter(uint32(a[0]), Surface{Proxy{ptr: a[1]}}, arrayBytes(a[2]))
			}
		case 2:
			if h.Leave != nil {
				h.Leave(uint32(a[0]), Surface{Proxy{ptr: a[1]}})
			}
		case 3:
			if h.Key != nil {
				h.Key(uint32(a[0]), uint32(a[1]), uint32(a[2]), uint32(a[3]))
			}
		case 4:
			if h.Modifiers != nil {
				h.Modifiers(uint32(a[0]), uint32(a[1]), uint32(a[2]), uint32(a[3]), uint32(a[4]))
			}
		case 5:
			if h.RepeatInfo != nil {
				h.RepeatInfo(int32(uint32(a[0])), int32(uint32(a[1])))
			}
		}
	})
}
