// Code generated by wlgen from wayland.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// Output is wl_output: compositor output region.
type Output struct{ Proxy }

// OutputInterface is the wl_interface table for wl_output.
var OutputInterface Interface

// Output.subpixel enum.
const (
	// unknown geometry
	OutputSubpixelUnknown = 0
	// no geometry
	OutputSubpixelNone = 1
	// horizontal RGB
	OutputSubpixelHorizontalRgb = 2
	// horizontal BGR
	OutputSubpixelHorizontalBgr = 3
	// vertical RGB
	OutputSubpixelVerticalRgb = 4
	// vertical BGR
	OutputSubpixelVerticalBgr = 5
)

// Output.transform enum.
const (
	// no transform
	OutputTransformNormal = 0
	// 90 degrees counter-clockwise
	OutputTransform90 = 1
	// 180 degrees counter-clockwise
	OutputTransform180 = 2
	// 270 degrees counter-clockwise
	OutputTransform270 = 3
	// 180 degree flip around a vertical axis
	OutputTransformFlipped = 4
	// flip and rotate 90 degrees counter-clockwise
	OutputTransformFlipped90 = 5
	// flip and rotate 180 degrees counter-clockwise
	OutputTransformFlipped180 = 6
	// flip and rotate 270 degrees counter-clockwise
	OutputTransformFlipped270 = 7
)

// Output.mode enum.
const (
	// indicates this is the current mode
	OutputModeCurrent = 0x1
	// indicates this is the preferred mode
	OutputModePreferred = 0x2
)

// Release sends wl_output.release: release the output object.
// Needs version 3 of the bound object.
// It destroys the proxy; do not use it afterwards.
func (px Output) Release() {
	px.marshal(0, nil, 0, marshalFlagDestroy)
}

// OutputHandlers holds one func per wl_output event. A nil func ignores the event.
// Strings and arrays are only valid until the func returns.
type OutputHandlers struct {
	// Geometry is wl_output.geometry: properties of the output.
	Geometry func(x int32, y int32, physicalWidth int32, physicalHeight int32, subpixel int32, make string, model string, transform int32)
	// Mode is wl_output.mode: advertise available modes for the output.
	Mode func(flags uint32, width int32, height int32, refresh int32)
	// Done is wl_output.done: sent all information about output.
	Done func()
	// Scale is wl_output.scale: output scaling properties.
	Scale func(factor int32)
	// Name is wl_output.name: name of this output.
	Name func(name string)
	// Description is wl_output.description: human-readable description of this output.
	Description func(description string)
}

// SetHandlers routes the events of px to h, replacing any earlier handlers.
func (px Output) SetHandlers(h OutputHandlers) { px.SetDispatcher(h.Dispatcher()) }

// OutputDispatcher is the decoder for OutputHandlers, built once by Dispatcher
// and installed on any number of proxies without allocating.
type OutputDispatcher struct {
	f func(opcode uint32, a *argSlots)
}

// SetDispatcher routes the events of px to d, replacing any earlier handlers.
func (px Output) SetDispatcher(d OutputDispatcher) { px.setDispatch(d.f) }

// Dispatcher builds the event decoder for h.
func (h OutputHandlers) Dispatcher() OutputDispatcher {
	return OutputDispatcher{func(opcode uint32, a *argSlots) {
		switch opcode {
		case 0:
			if h.Geometry != nil {
				h.Geometry(int32(uint32(a[0])), int32(uint32(a[1])), int32(uint32(a[2])), int32(uint32(a[3])), int32(uint32(a[4])), goString(a[5]), goString(a[6]), int32(uint32(a[7])))
			}
		case 1:
			if h.Mode != nil {
				h.Mode(uint32(a[0]), int32(uint32(a[1])), int32(uint32(a[2])), int32(uint32(a[3])))
			}
		case 2:
			if h.Done != nil {
				h.Done()
			}
		case 3:
			if h.Scale != nil {
				h.Scale(int32(uint32(a[0])))
			}
		case 4:
			if h.Name != nil {
				h.Name(goString(a[0]))
			}
		case 5:
			if h.Description != nil {
				h.Description(goString(a[0]))
			}
		}
	}}
}
