// Code generated by wlgen from wayland.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// Pointer is wl_pointer: pointer input device.
type Pointer struct{ Proxy }

// PointerInterface is the wl_interface table for wl_pointer.
var PointerInterface Interface

// Pointer.error enum.
const (
	// given wl_surface has another role
	PointerErrorRole = 0
)

// Pointer.button_state enum.
const (
	// the button is not pressed
	PointerButtonStateReleased = 0
	// the button is pressed
	PointerButtonStatePressed = 1
)

// Pointer.axis enum.
const (
	// vertical axis
	PointerAxisVerticalScroll = 0
	// horizontal axis
	PointerAxisHorizontalScroll = 1
)

// Pointer.axis_source enum.
const (
	// a physical wheel rotation
	PointerAxisSourceWheel = 0
	// finger on a touch surface
	PointerAxisSourceFinger = 1
	// continuous coordinate space
	PointerAxisSourceContinuous = 2
	// a physical wheel tilt
	PointerAxisSourceWheelTilt = 3
)

// Pointer.axis_relative_direction enum.
const (
	// physical motion matches axis direction
	PointerAxisRelativeDirectionIdentical = 0
	// physical motion is the inverse of the axis direction
	PointerAxisRelativeDirectionInverted = 1
)

// SetCursor sends wl_pointer.set_cursor: set the pointer surface.
func (px Pointer) SetCursor(serial uint32, surface Surface, hotspotX int32, hotspotY int32) {
	px.marshal(0, nil, 0, 0, uintptr(serial), surface.ptr, uintptr(uint32(hotspotX)), uintptr(uint32(hotspotY)))
}

// Release sends wl_pointer.release: release the pointer object.
// Needs version 3 of the bound object.
// It destroys the proxy; do not use it afterwards.
func (px Pointer) Release() {
	px.marshal(1, nil, 0, marshalFlagDestroy)
}

// PointerHandlers holds one func per wl_pointer event. A nil func ignores the event.
// Strings and arrays are only valid until the func returns.
type PointerHandlers struct {
	// Enter is wl_pointer.enter: enter event.
	Enter func(serial uint32, surface Surface, surfaceX Fixed, surfaceY Fixed)
	// Leave is wl_pointer.leave: leave event.
	Leave func(serial uint32, surface Surface)
	// Motion is wl_pointer.motion: pointer motion event.
	Motion func(time uint32, surfaceX Fixed, surfaceY Fixed)
	// Button is wl_pointer.button: pointer button event.
	Button func(serial uint32, time uint32, button uint32, state uint32)
	// Axis is wl_pointer.axis: axis event.
	Axis func(time uint32, axis uint32, value Fixed)
	// Frame is wl_pointer.frame: end of a pointer event sequence.
	Frame func()
	// AxisSource is wl_pointer.axis_source: axis source event.
	AxisSource func(axisSource uint32)
	// AxisStop is wl_pointer.axis_stop: axis stop event.
	AxisStop func(time uint32, axis uint32)
	// AxisDiscrete is wl_pointer.axis_discrete: axis click event.
	AxisDiscrete func(axis uint32, discrete int32)
	// AxisValue120 is wl_pointer.axis_value120: axis high-resolution scroll event.
	AxisValue120 func(axis uint32, value120 int32)
	// AxisRelativeDirection is wl_pointer.axis_relative_direction: axis relative physical direction event.
	AxisRelativeDirection func(axis uint32, direction uint32)
}

// SetHandlers routes the events of px to h, replacing any earlier handlers.
func (px Pointer) SetHandlers(h PointerHandlers) { px.SetDispatcher(h.Dispatcher()) }

// PointerDispatcher is the decoder for PointerHandlers, built once by Dispatcher
// and installed on any number of proxies without allocating.
type PointerDispatcher struct {
	f func(opcode uint32, a *argSlots)
}

// SetDispatcher routes the events of px to d, replacing any earlier handlers.
func (px Pointer) SetDispatcher(d PointerDispatcher) { px.setDispatch(d.f) }

// Dispatcher builds the event decoder for h.
func (h PointerHandlers) Dispatcher() PointerDispatcher {
	return PointerDispatcher{func(opcode uint32, a *argSlots) {
		switch opcode {
		case 0:
			if h.Enter != nil {
				h.Enter(uint32(a[0]), Surface{Proxy{ptr: a[1]}}, Fixed(int32(uint32(a[2]))), Fixed(int32(uint32(a[3]))))
			}
		case 1:
			if h.Leave != nil {
				h.Leave(uint32(a[0]), Surface{Proxy{ptr: a[1]}})
			}
		case 2:
			if h.Motion != nil {
				h.Motion(uint32(a[0]), Fixed(int32(uint32(a[1]))), Fixed(int32(uint32(a[2]))))
			}
		case 3:
			if h.Button != nil {
				h.Button(uint32(a[0]), uint32(a[1]), uint32(a[2]), uint32(a[3]))
			}
		case 4:
			if h.Axis != nil {
				h.Axis(uint32(a[0]), uint32(a[1]), Fixed(int32(uint32(a[2]))))
			}
		case 5:
			if h.Frame != nil {
				h.Frame()
			}
		case 6:
			if h.AxisSource != nil {
				h.AxisSource(uint32(a[0]))
			}
		case 7:
			if h.AxisStop != nil {
				h.AxisStop(uint32(a[0]), uint32(a[1]))
			}
		case 8:
			if h.AxisDiscrete != nil {
				h.AxisDiscrete(uint32(a[0]), int32(uint32(a[1])))
			}
		case 9:
			if h.AxisValue120 != nil {
				h.AxisValue120(uint32(a[0]), int32(uint32(a[1])))
			}
		case 10:
			if h.AxisRelativeDirection != nil {
				h.AxisRelativeDirection(uint32(a[0]), uint32(a[1]))
			}
		}
	}}
}
