// Code generated by wlgen from wayland.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// Registry is wl_registry: global registry object.
type Registry struct{ Proxy }

// RegistryInterface is the wl_interface table for wl_registry.
var RegistryInterface Interface

// Bind sends wl_registry.bind: bind an object to the display.
func (px Registry) Bind(name uint32, iface *Interface, version uint32) Proxy {
	r := px.marshal(0, iface, version, 0, uintptr(name), uintptr(unsafe.Pointer(iface.name)), uintptr(version), 0)
	return Proxy{ptr: r, ver: version}
}

// RegistryHandlers holds one func per wl_registry event. A nil func ignores the event.
// Strings and arrays are only valid until the func returns.
type RegistryHandlers struct {
	// Global is wl_registry.global: announce global object.
	Global func(name uint32, interface_ string, version_ uint32)
	// GlobalRemove is wl_registry.global_remove: announce removal of global object.
	GlobalRemove func(name uint32)
}

// SetHandlers routes the events of px to h, replacing any earlier handlers.
func (px Registry) SetHandlers(h RegistryHandlers) { px.SetDispatcher(h.Dispatcher()) }

// RegistryDispatcher is the decoder for RegistryHandlers, built once by Dispatcher
// and installed on any number of proxies without allocating.
type RegistryDispatcher struct {
	f func(opcode uint32, a *argSlots)
}

// SetDispatcher routes the events of px to d, replacing any earlier handlers.
func (px Registry) SetDispatcher(d RegistryDispatcher) { px.setDispatch(d.f) }

// Dispatcher builds the event decoder for h.
func (h RegistryHandlers) Dispatcher() RegistryDispatcher {
	return RegistryDispatcher{func(opcode uint32, a *argSlots) {
		switch opcode {
		case 0:
			if h.Global != nil {
				h.Global(uint32(a[0]), goString(a[1]), uint32(a[2]))
			}
		case 1:
			if h.GlobalRemove != nil {
				h.GlobalRemove(uint32(a[0]))
			}
		}
	}}
}
