// Code generated by wlgen from wayland.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// Region is wl_region: region interface.
type Region struct{ Proxy }

// RegionInterface is the wl_interface table for wl_region.
var RegionInterface Interface

// Destroy sends wl_region.destroy: destroy region.
// It destroys the proxy; do not use it afterwards.
func (px Region) Destroy() {
	px.marshal(0, nil, 0, marshalFlagDestroy)
}

// Add sends wl_region.add: add rectangle to region.
func (px Region) Add(x int32, y int32, width int32, height int32) {
	px.marshal(1, nil, 0, 0, uintptr(uint32(x)), uintptr(uint32(y)), uintptr(uint32(width)), uintptr(uint32(height)))
}

// Subtract sends wl_region.subtract: subtract rectangle from region.
func (px Region) Subtract(x int32, y int32, width int32, height int32) {
	px.marshal(2, nil, 0, 0, uintptr(uint32(x)), uintptr(uint32(y)), uintptr(uint32(width)), uintptr(uint32(height)))
}
