// Code generated by wlgen from wayland.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// Surface is wl_surface: an onscreen surface.
type Surface struct{ Proxy }

// SurfaceInterface is the wl_interface table for wl_surface.
var SurfaceInterface Interface

// Surface.error enum.
const (
	// buffer scale value is invalid
	SurfaceErrorInvalidScale = 0
	// buffer transform value is invalid
	SurfaceErrorInvalidTransform = 1
	// buffer size is invalid
	SurfaceErrorInvalidSize = 2
	// buffer offset is invalid
	SurfaceErrorInvalidOffset = 3
	// surface was destroyed before its role object
	SurfaceErrorDefunctRoleObject = 4
)

// Destroy sends wl_surface.destroy: delete surface.
// It destroys the proxy; do not use it afterwards.
func (px Surface) Destroy() {
	px.marshal(0, nil, 0, marshalFlagDestroy)
}

// Attach sends wl_surface.attach: set the surface contents.
func (px Surface) Attach(buffer Buffer, x int32, y int32) {
	px.marshal(1, nil, 0, 0, buffer.ptr, uintptr(uint32(x)), uintptr(uint32(y)))
}

// Damage sends wl_surface.damage: mark part of the surface damaged.
func (px Surface) Damage(x int32, y int32, width int32, height int32) {
	px.marshal(2, nil, 0, 0, uintptr(uint32(x)), uintptr(uint32(y)), uintptr(uint32(width)), uintptr(uint32(height)))
}

// Frame sends wl_surface.frame: request a frame throttling hint.
func (px Surface) Frame() Callback {
	ver := px.Version()
	r := px.marshal(3, &CallbackInterface, ver, 0, 0)
	return Callback{Proxy{ptr: r, ver: ver}}
}

// SetOpaqueRegion sends wl_surface.set_opaque_region: set opaque region.
func (px Surface) SetOpaqueRegion(region Region) {
	px.marshal(4, nil, 0, 0, region.ptr)
}

// SetInputRegion sends wl_surface.set_input_region: set input region.
func (px Surface) SetInputRegion(region Region) {
	px.marshal(5, nil, 0, 0, region.ptr)
}

// Commit sends wl_surface.commit: commit pending surface state.
func (px Surface) Commit() {
	px.marshal(6, nil, 0, 0)
}

// SetBufferTransform sends wl_surface.set_buffer_transform: sets the buffer transformation.
// Needs version 2 of the bound object.
func (px Surface) SetBufferTransform(transform int32) {
	px.marshal(7, nil, 0, 0, uintptr(uint32(transform)))
}

// SetBufferScale sends wl_surface.set_buffer_scale: sets the buffer scaling factor.
// Needs version 3 of the bound object.
func (px Surface) SetBufferScale(scale int32) {
	px.marshal(8, nil, 0, 0, uintptr(uint32(scale)))
}

// DamageBuffer sends wl_surface.damage_buffer: mark part of the surface damaged using buffer coordinates.
// Needs version 4 of the bound object.
func (px Surface) DamageBuffer(x int32, y int32, width int32, height int32) {
	px.marshal(9, nil, 0, 0, uintptr(uint32(x)), uintptr(uint32(y)), uintptr(uint32(width)), uintptr(uint32(height)))
}

// Offset sends wl_surface.offset: set the surface contents offset.
// Needs version 5 of the bound object.
func (px Surface) Offset(x int32, y int32) {
	px.marshal(10, nil, 0, 0, uintptr(uint32(x)), uintptr(uint32(y)))
}

// SurfaceHandlers holds one func per wl_surface event. A nil func ignores the event.
// Strings and arrays are only valid until the func returns.
type SurfaceHandlers struct {
	// Enter is wl_surface.enter: surface enters an output.
	Enter func(output Output)
	// Leave is wl_surface.leave: surface leaves an output.
	Leave func(output Output)
	// PreferredBufferScale is wl_surface.preferred_buffer_scale: preferred buffer scale for the surface.
	PreferredBufferScale func(factor int32)
	// PreferredBufferTransform is wl_surface.preferred_buffer_transform: preferred buffer transform for the surface.
	PreferredBufferTransform func(transform uint32)
}

// SetHandlers routes the events of px to h, replacing any earlier handlers.
func (px Surface) SetHandlers(h SurfaceHandlers) {
	px.setDispatch(func(opcode uint32, a *argSlots) {
		switch opcode {
		case 0:
			if h.Enter != nil {
				h.Enter(Output{Proxy{ptr: a[0]}})
			}
		case 1:
			if h.Leave != nil {
				h.Leave(Output{Proxy{ptr: a[0]}})
			}
		case 2:
			if h.PreferredBufferScale != nil {
				h.PreferredBufferScale(int32(uint32(a[0])))
			}
		case 3:
			if h.PreferredBufferTransform != nil {
				h.PreferredBufferTransform(uint32(a[0]))
			}
		}
	})
}
