// Code generated by wlgen from wayland.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// ShmPool is wl_shm_pool: a shared memory pool.
type ShmPool struct{ Proxy }

// ShmPoolInterface is the wl_interface table for wl_shm_pool.
var ShmPoolInterface Interface

// CreateBuffer sends wl_shm_pool.create_buffer: create a buffer from the pool.
func (px ShmPool) CreateBuffer(offset int32, width int32, height int32, stride int32, format uint32) Buffer {
	ver := px.Version()
	r := px.marshal(0, &BufferInterface, ver, 0, 0, uintptr(uint32(offset)), uintptr(uint32(width)), uintptr(uint32(height)), uintptr(uint32(stride)), uintptr(format))
	return Buffer{Proxy{ptr: r, ver: ver}}
}

// Destroy sends wl_shm_pool.destroy: destroy the pool.
// It destroys the proxy; do not use it afterwards.
func (px ShmPool) Destroy() {
	px.marshal(1, nil, 0, marshalFlagDestroy)
}

// Resize sends wl_shm_pool.resize: change the size of the pool mapping.
func (px ShmPool) Resize(size int32) {
	px.marshal(2, nil, 0, 0, uintptr(uint32(size)))
}
