// Code generated by wlgen from wayland.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// Subcompositor is wl_subcompositor: sub-surface compositing.
type Subcompositor struct{ Proxy }

// SubcompositorInterface is the wl_interface table for wl_subcompositor.
var SubcompositorInterface Interface

// Subcompositor.error enum.
const (
	// the to-be sub-surface is invalid
	SubcompositorErrorBadSurface = 0
	// the to-be sub-surface parent is invalid
	SubcompositorErrorBadParent = 1
)

// Destroy sends wl_subcompositor.destroy: unbind from the subcompositor interface.
// It destroys the proxy; do not use it afterwards.
func (px Subcompositor) Destroy() {
	px.marshal(0, nil, 0, marshalFlagDestroy)
}

// GetSubsurface sends wl_subcompositor.get_subsurface: give a surface the role sub-surface.
func (px Subcompositor) GetSubsurface(surface Surface, parent Surface) Subsurface {
	ver := px.Version()
	r := px.marshal(1, &SubsurfaceInterface, ver, 0, 0, surface.ptr, parent.ptr)
	return Subsurface{Proxy{ptr: r, ver: ver}}
}
