// Code generated by wlgen from wayland.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// Subsurface is wl_subsurface: sub-surface interface to a wl_surface.
type Subsurface struct{ Proxy }

// SubsurfaceInterface is the wl_interface table for wl_subsurface.
var SubsurfaceInterface Interface

// Subsurface.error enum.
const (
	// wl_surface is not a sibling or the parent
	SubsurfaceErrorBadSurface = 0
)

// Destroy sends wl_subsurface.destroy: remove sub-surface interface.
// It destroys the proxy; do not use it afterwards.
func (px Subsurface) Destroy() {
	px.marshal(0, nil, 0, marshalFlagDestroy)
}

// SetPosition sends wl_subsurface.set_position: reposition the sub-surface.
func (px Subsurface) SetPosition(x int32, y int32) {
	px.marshal(1, nil, 0, 0, uintptr(uint32(x)), uintptr(uint32(y)))
}

// PlaceAbove sends wl_subsurface.place_above: restack the sub-surface.
func (px Subsurface) PlaceAbove(sibling Surface) {
	px.marshal(2, nil, 0, 0, sibling.ptr)
}

// PlaceBelow sends wl_subsurface.place_below: restack the sub-surface.
func (px Subsurface) PlaceBelow(sibling Surface) {
	px.marshal(3, nil, 0, 0, sibling.ptr)
}

// SetSync sends wl_subsurface.set_sync: set sub-surface to synchronized mode.
func (px Subsurface) SetSync() {
	px.marshal(4, nil, 0, 0)
}

// SetDesync sends wl_subsurface.set_desync: set sub-surface to desynchronized mode.
func (px Subsurface) SetDesync() {
	px.marshal(5, nil, 0, 0)
}
