// Code generated by wlgen from wayland.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// ShellSurface is wl_shell_surface: desktop-style metadata interface.
type ShellSurface struct{ Proxy }

// ShellSurfaceInterface is the wl_interface table for wl_shell_surface.
var ShellSurfaceInterface Interface

// ShellSurface.resize enum.
const (
	// no edge
	ShellSurfaceResizeNone = 0
	// top edge
	ShellSurfaceResizeTop = 1
	// bottom edge
	ShellSurfaceResizeBottom = 2
	// left edge
	ShellSurfaceResizeLeft = 4
	// top and left edges
	ShellSurfaceResizeTopLeft = 5
	// bottom and left edges
	ShellSurfaceResizeBottomLeft = 6
	// right edge
	ShellSurfaceResizeRight = 8
	// top and right edges
	ShellSurfaceResizeTopRight = 9
	// bottom and right edges
	ShellSurfaceResizeBottomRight = 10
)

// ShellSurface.transient enum.
const (
	// do not set keyboard focus
	ShellSurfaceTransientInactive = 0x1
)

// ShellSurface.fullscreen_method enum.
const (
	// no preference, apply default policy
	ShellSurfaceFullscreenMethodDefault = 0
	// scale, preserve the surface's aspect ratio and center on output
	ShellSurfaceFullscreenMethodScale = 1
	// switch output mode to the smallest mode that can fit the surface, add black borders to compensate size mismatch
	ShellSurfaceFullscreenMethodDriver = 2
	// no upscaling, center on output and add black borders to compensate size mismatch
	ShellSurfaceFullscreenMethodFill = 3
)

// Pong sends wl_shell_surface.pong: respond to a ping event.
func (px ShellSurface) Pong(serial uint32) {
	px.marshal(0, nil, 0, 0, uintptr(serial))
}

// Move sends wl_shell_surface.move: start an interactive move.
func (px ShellSurface) Move(seat Seat, serial uint32) {
	px.marshal(1, nil, 0, 0, seat.ptr, uintptr(serial))
}

// Resize sends wl_shell_surface.resize: start an interactive resize.
func (px ShellSurface) Resize(seat Seat, serial uint32, edges uint32) {
	px.marshal(2, nil, 0, 0, seat.ptr, uintptr(serial), uintptr(edges))
}

// SetToplevel sends wl_shell_surface.set_toplevel: make the surface a toplevel surface.
func (px ShellSurface) SetToplevel() {
	px.marshal(3, nil, 0, 0)
}

// SetTransient sends wl_shell_surface.set_transient: make the surface a transient surface.
func (px ShellSurface) SetTransient(parent Surface, x int32, y int32, flags uint32) {
	px.marshal(4, nil, 0, 0, parent.ptr, uintptr(uint32(x)), uintptr(uint32(y)), uintptr(flags))
}

// SetFullscreen sends wl_shell_surface.set_fullscreen: make the surface a fullscreen surface.
func (px ShellSurface) SetFullscreen(method uint32, framerate uint32, output Output) {
	px.marshal(5, nil, 0, 0, uintptr(method), uintptr(framerate), output.ptr)
}

// SetPopup sends wl_shell_surface.set_popup: make the surface a popup surface.
func (px ShellSurface) SetPopup(seat Seat, serial uint32, parent Surface, x int32, y int32, flags uint32) {
	px.marshal(6, nil, 0, 0, seat.ptr, uintptr(serial), parent.ptr, uintptr(uint32(x)), uintptr(uint32(y)), uintptr(flags))
}

// SetMaximized sends wl_shell_surface.set_maximized: make the surface a maximized surface.
func (px ShellSurface) SetMaximized(output Output) {
	px.marshal(7, nil, 0, 0, output.ptr)
}

// SetTitle sends wl_shell_surface.set_title: set surface title.
func (px ShellSurface) SetTitle(title string) {
	titleC := cString(title, false)
	px.marshal(8, nil, 0, 0, cStringPtr(titleC))
	runtime.KeepAlive(titleC)
}

// SetClass sends wl_shell_surface.set_class: set surface class.
func (px ShellSurface) SetClass(class string) {
	classC := cString(class, false)
	px.marshal(9, nil, 0, 0, cStringPtr(classC))
	runtime.KeepAlive(classC)
}

// ShellSurfaceHandlers holds one func per wl_shell_surface event. A nil func ignores the event.
// Strings and arrays are only valid until the func returns.
type ShellSurfaceHandlers struct {
	// Ping is wl_shell_surface.ping: ping client.
	Ping func(serial uint32)
	// Configure is wl_shell_surface.configure: suggest resize.
	Configure func(edges uint32, width int32, height int32)
	// PopupDone is wl_shell_surface.popup_done: popup interaction is done.
	PopupDone func()
}

// SetHandlers routes the events of px to h, replacing any earlier handlers.
func (px ShellSurface) SetHandlers(h ShellSurfaceHandlers) { px.SetDispatcher(h.Dispatcher()) }

// ShellSurfaceDispatcher is the decoder for ShellSurfaceHandlers, built once by Dispatcher
// and installed on any number of proxies without allocating.
type ShellSurfaceDispatcher struct {
	f func(opcode uint32, a *argSlots)
}

// SetDispatcher routes the events of px to d, replacing any earlier handlers.
func (px ShellSurface) SetDispatcher(d ShellSurfaceDispatcher) { px.setDispatch(d.f) }

// Dispatcher builds the event decoder for h.
func (h ShellSurfaceHandlers) Dispatcher() ShellSurfaceDispatcher {
	return ShellSurfaceDispatcher{func(opcode uint32, a *argSlots) {
		switch opcode {
		case 0:
			if h.Ping != nil {
				h.Ping(uint32(a[0]))
			}
		case 1:
			if h.Configure != nil {
				h.Configure(uint32(a[0]), int32(uint32(a[1])), int32(uint32(a[2])))
			}
		case 2:
			if h.PopupDone != nil {
				h.PopupDone()
			}
		}
	}}
}
