// Code generated by wlgen from wayland.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// Shm is wl_shm: shared memory support.
type Shm struct{ Proxy }

// ShmInterface is the wl_interface table for wl_shm.
var ShmInterface Interface

// Shm.error enum.
const (
	// buffer format is not known
	ShmErrorInvalidFormat = 0
	// invalid size or stride during pool or buffer creation
	ShmErrorInvalidStride = 1
	// mmapping the file descriptor failed
	ShmErrorInvalidFd = 2
)

// Shm.format enum.
const (
	// 32-bit ARGB format, [31:0] A:R:G:B 8:8:8:8 little endian
	ShmFormatArgb8888 = 0
	// 32-bit RGB format, [31:0] x:R:G:B 8:8:8:8 little endian
	ShmFormatXrgb8888 = 1
	// 8-bit color index format, [7:0] C
	ShmFormatC8 = 0x20203843
	// 8-bit RGB format, [7:0] R:G:B 3:3:2
	ShmFormatRgb332 = 0x38424752
	// 8-bit BGR format, [7:0] B:G:R 2:3:3
	ShmFormatBgr233 = 0x38524742
	// 16-bit xRGB format, [15:0] x:R:G:B 4:4:4:4 little endian
	ShmFormatXrgb4444 = 0x32315258
	// 16-bit xBGR format, [15:0] x:B:G:R 4:4:4:4 little endian
	ShmFormatXbgr4444 = 0x32314258
	// 16-bit RGBx format, [15:0] R:G:B:x 4:4:4:4 little endian
	ShmFormatRgbx4444 = 0x32315852
	// 16-bit BGRx format, [15:0] B:G:R:x 4:4:4:4 little endian
	ShmFormatBgrx4444 = 0x32315842
	// 16-bit ARGB format, [15:0] A:R:G:B 4:4:4:4 little endian
	ShmFormatArgb4444 = 0x32315241
	// 16-bit ABGR format, [15:0] A:B:G:R 4:4:4:4 little endian
	ShmFormatAbgr4444 = 0x32314241
	// 16-bit RBGA format, [15:0] R:G:B:A 4:4:4:4 little endian
	ShmFormatRgba4444 = 0x32314152
	// 16-bit BGRA format, [15:0] B:G:R:A 4:4:4:4 little endian
	ShmFormatBgra4444 = 0x32314142
	// 16-bit xRGB format, [15:0] x:R:G:B 1:5:5:5 little endian
	ShmFormatXrgb1555 = 0x35315258
	// 16-bit xBGR 1555 format, [15:0] x:B:G:R 1:5:5:5 little endian
	ShmFormatXbgr1555 = 0x35314258
	// 16-bit RGBx 5551 format, [15:0] R:G:B:x 5:5:5:1 little endian
	ShmFormatRgbx5551 = 0x35315852
	// 16-bit BGRx 5551 format, [15:0] B:G:R:x 5:5:5:1 little endian
	ShmFormatBgrx5551 = 0x35315842
	// 16-bit ARGB 1555 format, [15:0] A:R:G:B 1:5:5:5 little endian
	ShmFormatArgb1555 = 0x35315241
	// 16-bit ABGR 1555 format, [15:0] A:B:G:R 1:5:5:5 little endian
	ShmFormatAbgr1555 = 0x35314241
	// 16-bit RGBA 5551 format, [15:0] R:G:B:A 5:5:5:1 little endian
	ShmFormatRgba5551 = 0x35314152
	// 16-bit BGRA 5551 format, [15:0] B:G:R:A 5:5:5:1 little endian
	ShmFormatBgra5551 = 0x35314142
	// 16-bit RGB 565 format, [15:0] R:G:B 5:6:5 little endian
	ShmFormatRgb565 = 0x36314752
	// 16-bit BGR 565 format, [15:0] B:G:R 5:6:5 little endian
	ShmFormatBgr565 = 0x36314742
	// 24-bit RGB format, [23:0] R:G:B little endian
	ShmFormatRgb888 = 0x34324752
	// 24-bit BGR format, [23:0] B:G:R little endian
	ShmFormatBgr888 = 0x34324742
	// 32-bit xBGR format, [31:0] x:B:G:R 8:8:8:8 little endian
	ShmFormatXbgr8888 = 0x34324258
	// 32-bit RGBx format, [31:0] R:G:B:x 8:8:8:8 little endian
	ShmFormatRgbx8888 = 0x34325852
	// 32-bit BGRx format, [31:0] B:G:R:x 8:8:8:8 little endian
	ShmFormatBgrx8888 = 0x34325842
	// 32-bit ABGR format, [31:0] A:B:G:R 8:8:8:8 little endian
	ShmFormatAbgr8888 = 0x34324241
	// 32-bit RGBA format, [31:0] R:G:B:A 8:8:8:8 little endian
	ShmFormatRgba8888 = 0x34324152
	// 32-bit BGRA format, [31:0] B:G:R:A 8:8:8:8 little endian
	ShmFormatBgra8888 = 0x34324142
	// 32-bit xRGB format, [31:0] x:R:G:B 2:10:10:10 little endian
	ShmFormatXrgb2101010 = 0x30335258
	// 32-bit xBGR format, [31:0] x:B:G:R 2:10:10:10 little endian
	ShmFormatXbgr2101010 = 0x30334258
	// 32-bit RGBx format, [31:0] R:G:B:x 10:10:10:2 little endian
	ShmFormatRgbx1010102 = 0x30335852
	// 32-bit BGRx format, [31:0] B:G:R:x 10:10:10:2 little endian
	ShmFormatBgrx1010102 = 0x30335842
	// 32-bit ARGB format, [31:0] A:R:G:B 2:10:10:10 little endian
	ShmFormatArgb2101010 = 0x30335241
	// 32-bit ABGR format, [31:0] A:B:G:R 2:10:10:10 little endian
	ShmFormatAbgr2101010 = 0x30334241
	// 32-bit RGBA format, [31:0] R:G:B:A 10:10:10:2 little endian
	ShmFormatRgba1010102 = 0x30334152
	// 32-bit BGRA format, [31:0] B:G:R:A 10:10:10:2 little endian
	ShmFormatBgra1010102 = 0x30334142
	// packed YCbCr format, [31:0] Cr0:Y1:Cb0:Y0 8:8:8:8 little endian
	ShmFormatYuyv = 0x56595559
	// packed YCbCr format, [31:0] Cb0:Y1:Cr0:Y0 8:8:8:8 little endian
	ShmFormatYvyu = 0x55595659
	// packed YCbCr format, [31:0] Y1:Cr0:Y0:Cb0 8:8:8:8 little endian
	ShmFormatUyvy = 0x59565955
	// packed YCbCr format, [31:0] Y1:Cb0:Y0:Cr0 8:8:8:8 little endian
	ShmFormatVyuy = 0x59555956
	// packed AYCbCr format, [31:0] A:Y:Cb:Cr 8:8:8:8 little endian
	ShmFormatAyuv = 0x56555941
	// 2 plane YCbCr Cr:Cb format, 2x2 subsampled Cr:Cb plane
	ShmFormatNv12 = 0x3231564e
	// 2 plane YCbCr Cb:Cr format, 2x2 subsampled Cb:Cr plane
	ShmFormatNv21 = 0x3132564e
	// 2 plane YCbCr Cr:Cb format, 2x1 subsampled Cr:Cb plane
	ShmFormatNv16 = 0x3631564e
	// 2 plane YCbCr Cb:Cr format, 2x1 subsampled Cb:Cr plane
	ShmFormatNv61 = 0x3136564e
	// 3 plane YCbCr format, 4x4 subsampled Cb (1) and Cr (2) planes
	ShmFormatYuv410 = 0x39565559
	// 3 plane YCbCr format, 4x4 subsampled Cr (1) and Cb (2) planes
	ShmFormatYvu410 = 0x39555659
	// 3 plane YCbCr format, 4x1 subsampled Cb (1) and Cr (2) planes
	ShmFormatYuv411 = 0x31315559
	// 3 plane YCbCr format, 4x1 subsampled Cr (1) and Cb (2) planes
	ShmFormatYvu411 = 0x31315659
	// 3 plane YCbCr format, 2x2 subsampled Cb (1) and Cr (2) planes
	ShmFormatYuv420 = 0x32315559
	// 3 plane YCbCr format, 2x2 subsampled Cr (1) and Cb (2) planes
	ShmFormatYvu420 = 0x32315659
	// 3 plane YCbCr format, 2x1 subsampled Cb (1) and Cr (2) planes
	ShmFormatYuv422 = 0x36315559
	// 3 plane YCbCr format, 2x1 subsampled Cr (1) and Cb (2) planes
	ShmFormatYvu422 = 0x36315659
	// 3 plane YCbCr format, non-subsampled Cb (1) and Cr (2) planes
	ShmFormatYuv444 = 0x34325559
	// 3 plane YCbCr format, non-subsampled Cr (1) and Cb (2) planes
	ShmFormatYvu444 = 0x34325659
	// [7:0] R
	ShmFormatR8 = 0x20203852
	// [15:0] R little endian
	ShmFormatR16 = 0x20363152
	// [15:0] R:G 8:8 little endian
	ShmFormatRg88 = 0x38384752
	// [15:0] G:R 8:8 little endian
	ShmFormatGr88 = 0x38385247
	// [31:0] R:G 16:16 little endian
	ShmFormatRg1616 = 0x32334752
	// [31:0] G:R 16:16 little endian
	ShmFormatGr1616 = 0x32335247
	// [63:0] x:R:G:B 16:16:16:16 little endian
	ShmFormatXrgb16161616f = 0x48345258
	// [63:0] x:B:G:R 16:16:16:16 little endian
	ShmFormatXbgr16161616f = 0x48344258
	// [63:0] A:R:G:B 16:16:16:16 little endian
	ShmFormatArgb16161616f = 0x48345241
	// [63:0] A:B:G:R 16:16:16:16 little endian
	ShmFormatAbgr16161616f = 0x48344241
	// [31:0] X:Y:Cb:Cr 8:8:8:8 little endian
	ShmFormatXyuv8888 = 0x56555958
	// [23:0] Cr:Cb:Y 8:8:8 little endian
	ShmFormatVuy888 = 0x34325556
	// Y followed by U then V, 10:10:10. Non-linear modifier only
	ShmFormatVuy101010 = 0x30335556
	// [63:0] Cr0:0:Y1:0:Cb0:0:Y0:0 10:6:10:6:10:6:10:6 little endian per 2 Y pixels
	ShmFormatY210 = 0x30313259
	// [63:0] Cr0:0:Y1:0:Cb0:0:Y0:0 12:4:12:4:12:4:12:4 little endian per 2 Y pixels
	ShmFormatY212 = 0x32313259
	// [63:0] Cr0:Y1:Cb0:Y0 16:16:16:16 little endian per 2 Y pixels
	ShmFormatY216 = 0x36313259
	// [31:0] A:Cr:Y:Cb 2:10:10:10 little endian
	ShmFormatY410 = 0x30313459
	// [63:0] A:0:Cr:0:Y:0:Cb:0 12:4:12:4:12:4:12:4 little endian
	ShmFormatY412 = 0x32313459
	// [63:0] A:Cr:Y:Cb 16:16:16:16 little endian
	ShmFormatY416 = 0x36313459
	// [31:0] X:Cr:Y:Cb 2:10:10:10 little endian
	ShmFormatXvyu2101010 = 0x30335658
	// [63:0] X:0:Cr:0:Y:0:Cb:0 12:4:12:4:12:4:12:4 little endian
	ShmFormatXvyu1216161616 = 0x36335658
	// [63:0] X:Cr:Y:Cb 16:16:16:16 little endian
	ShmFormatXvyu16161616 = 0x38345658
	// [63:0] A3:A2:Y3:0:Cr0:0:Y2:0:A1:A0:Y1:0:Cb0:0:Y0:0 1:1:8:2:8:2:8:2:1:1:8:2:8:2:8:2 little endian
	ShmFormatY0l0 = 0x304c3059
	// [63:0] X3:X2:Y3:0:Cr0:0:Y2:0:X1:X0:Y1:0:Cb0:0:Y0:0 1:1:8:2:8:2:8:2:1:1:8:2:8:2:8:2 little endian
	ShmFormatX0l0 = 0x304c3058
	// [63:0] A3:A2:Y3:Cr0:Y2:A1:A0:Y1:Cb0:Y0 1:1:10:10:10:1:1:10:10:10 little endian
	ShmFormatY0l2 = 0x324c3059
	// [63:0] X3:X2:Y3:Cr0:Y2:X1:X0:Y1:Cb0:Y0 1:1:10:10:10:1:1:10:10:10 little endian
	ShmFormatX0l2        = 0x324c3058
	ShmFormatYuv4208bit  = 0x38305559
	ShmFormatYuv42010bit = 0x30315559
	ShmFormatXrgb8888A8  = 0x38415258
	ShmFormatXbgr8888A8  = 0x38414258
	ShmFormatRgbx8888A8  = 0x38415852
	ShmFormatBgrx8888A8  = 0x38415842
	ShmFormatRgb888A8    = 0x38413852
	ShmFormatBgr888A8    = 0x38413842
	ShmFormatRgb565A8    = 0x38413552
	ShmFormatBgr565A8    = 0x38413542
	// non-subsampled Cr:Cb plane
	ShmFormatNv24 = 0x3432564e
	// non-subsampled Cb:Cr plane
	ShmFormatNv42 = 0x3234564e
	// 2x1 subsampled Cr:Cb plane, 10 bit per channel
	ShmFormatP210 = 0x30313250
	// 2x2 subsampled Cr:Cb plane 10 bits per channel
	ShmFormatP010 = 0x30313050
	// 2x2 subsampled Cr:Cb plane 12 bits per channel
	ShmFormatP012 = 0x32313050
	// 2x2 subsampled Cr:Cb plane 16 bits per channel
	ShmFormatP016 = 0x36313050
	// [63:0] A:x:B:x:G:x:R:x 10:6:10:6:10:6:10:6 little endian
	ShmFormatAxbxgxrx106106106106 = 0x30314241
	// 2x2 subsampled Cr:Cb plane
	ShmFormatNv15 = 0x3531564e
	ShmFormatQ410 = 0x30313451
	ShmFormatQ401 = 0x31303451
	// [63:0] x:R:G:B 16:16:16:16 little endian
	ShmFormatXrgb16161616 = 0x38345258
	// [63:0] x:B:G:R 16:16:16:16 little endian
	ShmFormatXbgr16161616 = 0x38344258
	// [63:0] A:R:G:B 16:16:16:16 little endian
	ShmFormatArgb16161616 = 0x38345241
	// [63:0] A:B:G:R 16:16:16:16 little endian
	ShmFormatAbgr16161616 = 0x38344241
	// [7:0] C0:C1:C2:C3:C4:C5:C6:C7 1:1:1:1:1:1:1:1 eight pixels/byte
	ShmFormatC1 = 0x20203143
	// [7:0] C0:C1:C2:C3 2:2:2:2 four pixels/byte
	ShmFormatC2 = 0x20203243
	// [7:0] C0:C1 4:4 two pixels/byte
	ShmFormatC4 = 0x20203443
	// [7:0] D0:D1:D2:D3:D4:D5:D6:D7 1:1:1:1:1:1:1:1 eight pixels/byte
	ShmFormatD1 = 0x20203144
	// [7:0] D0:D1:D2:D3 2:2:2:2 four pixels/byte
	ShmFormatD2 = 0x20203244
	// [7:0] D0:D1 4:4 two pixels/byte
	ShmFormatD4 = 0x20203444
	// [7:0] D
	ShmFormatD8 = 0x20203844
	// [7:0] R0:R1:R2:R3:R4:R5:R6:R7 1:1:1:1:1:1:1:1 eight pixels/byte
	ShmFormatR1 = 0x20203152
	// [7:0] R0:R1:R2:R3 2:2:2:2 four pixels/byte
	ShmFormatR2 = 0x20203252
	// [7:0] R0:R1 4:4 two pixels/byte
	ShmFormatR4 = 0x20203452
	// [15:0] x:R 6:10 little endian
	ShmFormatR10 = 0x20303152
	// [15:0] x:R 4:12 little endian
	ShmFormatR12 = 0x20323152
	// [31:0] A:Cr:Cb:Y 8:8:8:8 little endian
	ShmFormatAvuy8888 = 0x59555641
	// [31:0] X:Cr:Cb:Y 8:8:8:8 little endian
	ShmFormatXvuy8888 = 0x59555658
	// 2x2 subsampled Cr:Cb plane 10 bits per channel packed
	ShmFormatP030 = 0x30333050
)

// CreatePool sends wl_shm.create_pool: create a shm pool.
func (px Shm) CreatePool(fd int, size int32) ShmPool {
	ver := px.Version()
	r := px.marshal(0, &ShmPoolInterface, ver, 0, 0, uintptr(fd), uintptr(uint32(size)))
	return ShmPool{Proxy{ptr: r, ver: ver}}
}

// Release sends wl_shm.release: release the shm object.
// Needs version 2 of the bound object.
// It destroys the proxy; do not use it afterwards.
func (px Shm) Release() {
	px.marshal(1, nil, 0, marshalFlagDestroy)
}

// ShmHandlers holds one func per wl_shm event. A nil func ignores the event.
// Strings and arrays are only valid until the func returns.
type ShmHandlers struct {
	// Format is wl_shm.format: pixel format description.
	Format func(format uint32)
}

// SetHandlers routes the events of px to h, replacing any earlier handlers.
func (px Shm) SetHandlers(h ShmHandlers) { px.SetDispatcher(h.Dispatcher()) }

// ShmDispatcher is the decoder for ShmHandlers, built once by Dispatcher
// and installed on any number of proxies without allocating.
type ShmDispatcher struct {
	f func(opcode uint32, a *argSlots)
}

// SetDispatcher routes the events of px to d, replacing any earlier handlers.
func (px Shm) SetDispatcher(d ShmDispatcher) { px.setDispatch(d.f) }

// Dispatcher builds the event decoder for h.
func (h ShmHandlers) Dispatcher() ShmDispatcher {
	return ShmDispatcher{func(opcode uint32, a *argSlots) {
		switch opcode {
		case 0:
			if h.Format != nil {
				h.Format(uint32(a[0]))
			}
		}
	}}
}
