// Code generated by wlgen from wayland.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// Seat is wl_seat: group of input devices.
type Seat struct{ Proxy }

// SeatInterface is the wl_interface table for wl_seat.
var SeatInterface Interface

// Seat.capability enum.
const (
	// the seat has pointer devices
	SeatCapabilityPointer = 1
	// the seat has one or more keyboards
	SeatCapabilityKeyboard = 2
	// the seat has touch devices
	SeatCapabilityTouch = 4
)

// Seat.error enum.
const (
	// get_pointer, get_keyboard or get_touch called on seat without the matching capability
	SeatErrorMissingCapability = 0
)

// GetPointer sends wl_seat.get_pointer: return pointer object.
func (px Seat) GetPointer() Pointer {
	ver := px.Version()
	r := px.marshal(0, &PointerInterface, ver, 0, 0)
	return Pointer{Proxy{ptr: r, ver: ver}}
}

// GetKeyboard sends wl_seat.get_keyboard: return keyboard object.
func (px Seat) GetKeyboard() Keyboard {
	ver := px.Version()
	r := px.marshal(1, &KeyboardInterface, ver, 0, 0)
	return Keyboard{Proxy{ptr: r, ver: ver}}
}

// GetTouch sends wl_seat.get_touch: return touch object.
func (px Seat) GetTouch() Touch {
	ver := px.Version()
	r := px.marshal(2, &TouchInterface, ver, 0, 0)
	return Touch{Proxy{ptr: r, ver: ver}}
}

// Release sends wl_seat.release: release the seat object.
// Needs version 5 of the bound object.
// It destroys the proxy; do not use it afterwards.
func (px Seat) Release() {
	px.marshal(3, nil, 0, marshalFlagDestroy)
}

// SeatHandlers holds one func per wl_seat event. A nil func ignores the event.
// Strings and arrays are only valid until the func returns.
type SeatHandlers struct {
	// Capabilities is wl_seat.capabilities: seat capabilities changed.
	Capabilities func(capabilities uint32)
	// Name is wl_seat.name: unique identifier for this seat.
	Name func(name string)
}

// SetHandlers routes the events of px to h, replacing any earlier handlers.
func (px Seat) SetHandlers(h SeatHandlers) {
	px.setDispatch(func(opcode uint32, a *argSlots) {
		switch opcode {
		case 0:
			if h.Capabilities != nil {
				h.Capabilities(uint32(a[0]))
			}
		case 1:
			if h.Name != nil {
				h.Name(goString(a[0]))
			}
		}
	})
}
