// Code generated by wlgen from wayland.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// Shell is wl_shell: create desktop-style surfaces.
type Shell struct{ Proxy }

// ShellInterface is the wl_interface table for wl_shell.
var ShellInterface Interface

// Shell.error enum.
const (
	// given wl_surface has another role
	ShellErrorRole = 0
)

// GetShellSurface sends wl_shell.get_shell_surface: create a shell surface from a surface.
func (px Shell) GetShellSurface(surface Surface) ShellSurface {
	ver := px.Version()
	r := px.marshal(0, &ShellSurfaceInterface, ver, 0, 0, surface.ptr)
	return ShellSurface{Proxy{ptr: r, ver: ver}}
}
