// Code generated by wlgen from wayland.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// Touch is wl_touch: touchscreen input device.
type Touch struct{ Proxy }

// TouchInterface is the wl_interface table for wl_touch.
var TouchInterface Interface

// Release sends wl_touch.release: release the touch object.
// Needs version 3 of the bound object.
// It destroys the proxy; do not use it afterwards.
func (px Touch) Release() {
	px.marshal(0, nil, 0, marshalFlagDestroy)
}

// TouchHandlers holds one func per wl_touch event. A nil func ignores the event.
// Strings and arrays are only valid until the func returns.
type TouchHandlers struct {
	// Down is wl_touch.down: touch down event and beginning of a touch sequence.
	Down func(serial uint32, time uint32, surface Surface, id int32, x Fixed, y Fixed)
	// Up is wl_touch.up: end of a touch event sequence.
	Up func(serial uint32, time uint32, id int32)
	// Motion is wl_touch.motion: update of touch point coordinates.
	Motion func(time uint32, id int32, x Fixed, y Fixed)
	// Frame is wl_touch.frame: end of touch frame event.
	Frame func()
	// Cancel is wl_touch.cancel: touch session cancelled.
	Cancel func()
	// Shape is wl_touch.shape: update shape of touch point.
	Shape func(id int32, major Fixed, minor Fixed)
	// Orientation is wl_touch.orientation: update orientation of touch point.
	Orientation func(id int32, orientation Fixed)
}

// SetHandlers routes the events of px to h, replacing any earlier handlers.
func (px Touch) SetHandlers(h TouchHandlers) { px.SetDispatcher(h.Dispatcher()) }

// TouchDispatcher is the decoder for TouchHandlers, built once by Dispatcher
// and installed on any number of proxies without allocating.
type TouchDispatcher struct {
	f func(opcode uint32, a *argSlots)
}

// SetDispatcher routes the events of px to d, replacing any earlier handlers.
func (px Touch) SetDispatcher(d TouchDispatcher) { px.setDispatch(d.f) }

// Dispatcher builds the event decoder for h.
func (h TouchHandlers) Dispatcher() TouchDispatcher {
	return TouchDispatcher{func(opcode uint32, a *argSlots) {
		switch opcode {
		case 0:
			if h.Down != nil {
				h.Down(uint32(a[0]), uint32(a[1]), Surface{Proxy{ptr: a[2]}}, int32(uint32(a[3])), Fixed(int32(uint32(a[4]))), Fixed(int32(uint32(a[5]))))
			}
		case 1:
			if h.Up != nil {
				h.Up(uint32(a[0]), uint32(a[1]), int32(uint32(a[2])))
			}
		case 2:
			if h.Motion != nil {
				h.Motion(uint32(a[0]), int32(uint32(a[1])), Fixed(int32(uint32(a[2]))), Fixed(int32(uint32(a[3]))))
			}
		case 3:
			if h.Frame != nil {
				h.Frame()
			}
		case 4:
			if h.Cancel != nil {
				h.Cancel()
			}
		case 5:
			if h.Shape != nil {
				h.Shape(int32(uint32(a[0])), Fixed(int32(uint32(a[1]))), Fixed(int32(uint32(a[2]))))
			}
		case 6:
			if h.Orientation != nil {
				h.Orientation(int32(uint32(a[0])), Fixed(int32(uint32(a[1]))))
			}
		}
	}}
}
