// Code generated by wlgen from wlr_virtual_pointer_unstable_v1.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

func defineWlrVirtualPointerUnstableV1() {
	defineInterface(&ZwlrVirtualPointerV1Interface, "zwlr_virtual_pointer_v1", 2,
		[]message{
			newMessage("motion", "uff", []*Interface{nil, nil, nil}),
			newMessage("motion_absolute", "uuuuu", []*Interface{nil, nil, nil, nil, nil}),
			newMessage("button", "uuu", []*Interface{nil, nil, nil}),
			newMessage("axis", "uuf", []*Interface{nil, nil, nil}),
			newMessage("frame", "", nil),
			newMessage("axis_source", "u", []*Interface{nil}),
			newMessage("axis_stop", "uu", []*Interface{nil, nil}),
			newMessage("axis_discrete", "uufi", []*Interface{nil, nil, nil, nil}),
			newMessage("destroy", "", nil),
		},
		nil,
	)
	defineInterface(&ZwlrVirtualPointerManagerV1Interface, "zwlr_virtual_pointer_manager_v1", 2,
		[]message{
			newMessage("create_virtual_pointer", "?on", []*Interface{&SeatInterface, &ZwlrVirtualPointerV1Interface}),
			newMessage("destroy", "", nil),
			newMessage("create_virtual_pointer_with_output", "2?o?on", []*Interface{&SeatInterface, &OutputInterface, &ZwlrVirtualPointerV1Interface}),
		},
		nil,
	)
}
