// Code generated by wlgen from cursor_shape_v1.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// WpCursorShapeManagerV1 is wp_cursor_shape_manager_v1: cursor shape manager.
type WpCursorShapeManagerV1 struct{ Proxy }

// WpCursorShapeManagerV1Interface is the wl_interface table for wp_cursor_shape_manager_v1.
var WpCursorShapeManagerV1Interface Interface

// Destroy sends wp_cursor_shape_manager_v1.destroy: destroy the manager.
// It destroys the proxy; do not use it afterwards.
func (px WpCursorShapeManagerV1) Destroy() {
	px.marshal(0, nil, 0, marshalFlagDestroy)
}

// GetPointer sends wp_cursor_shape_manager_v1.get_pointer: manage the cursor shape of a pointer device.
func (px WpCursorShapeManagerV1) GetPointer(pointer Pointer) WpCursorShapeDeviceV1 {
	ver := px.Version()
	r := px.marshal(1, &WpCursorShapeDeviceV1Interface, ver, 0, 0, pointer.ptr)
	return WpCursorShapeDeviceV1{Proxy{ptr: r, ver: ver}}
}

// GetTabletToolV2 sends wp_cursor_shape_manager_v1.get_tablet_tool_v2: manage the cursor shape of a tablet tool device.
func (px WpCursorShapeManagerV1) GetTabletToolV2(tabletTool Proxy) WpCursorShapeDeviceV1 {
	ver := px.Version()
	r := px.marshal(2, &WpCursorShapeDeviceV1Interface, ver, 0, 0, tabletTool.ptr)
	return WpCursorShapeDeviceV1{Proxy{ptr: r, ver: ver}}
}
