// Code generated by wlgen from cursor_shape_v1.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// WpCursorShapeDeviceV1 is wp_cursor_shape_device_v1: cursor shape for a device.
type WpCursorShapeDeviceV1 struct{ Proxy }

// WpCursorShapeDeviceV1Interface is the wl_interface table for wp_cursor_shape_device_v1.
var WpCursorShapeDeviceV1Interface Interface

// WpCursorShapeDeviceV1.shape enum.
const (
	// default cursor
	WpCursorShapeDeviceV1ShapeDefault = 1
	// a context menu is available for the object under the cursor
	WpCursorShapeDeviceV1ShapeContextMenu = 2
	// help is available for the object under the cursor
	WpCursorShapeDeviceV1ShapeHelp = 3
	// pointer that indicates a link or another interactive element
	WpCursorShapeDeviceV1ShapePointer = 4
	// progress indicator
	WpCursorShapeDeviceV1ShapeProgress = 5
	// program is busy, user should wait
	WpCursorShapeDeviceV1ShapeWait = 6
	// a cell or set of cells may be selected
	WpCursorShapeDeviceV1ShapeCell = 7
	// simple crosshair
	WpCursorShapeDeviceV1ShapeCrosshair = 8
	// text may be selected
	WpCursorShapeDeviceV1ShapeText = 9
	// vertical text may be selected
	WpCursorShapeDeviceV1ShapeVerticalText = 10
	// drag-and-drop: alias of/shortcut to something is to be created
	WpCursorShapeDeviceV1ShapeAlias = 11
	// drag-and-drop: something is to be copied
	WpCursorShapeDeviceV1ShapeCopy = 12
	// drag-and-drop: something is to be moved
	WpCursorShapeDeviceV1ShapeMove = 13
	// drag-and-drop: the dragged item cannot be dropped at the current cursor location
	WpCursorShapeDeviceV1ShapeNoDrop = 14
	// drag-and-drop: the requested action will not be carried out
	WpCursorShapeDeviceV1ShapeNotAllowed = 15
	// drag-and-drop: something can be grabbed
	WpCursorShapeDeviceV1ShapeGrab = 16
	// drag-and-drop: something is being grabbed
	WpCursorShapeDeviceV1ShapeGrabbing = 17
	// resizing: the east border is to be moved
	WpCursorShapeDeviceV1ShapeEResize = 18
	// resizing: the north border is to be moved
	WpCursorShapeDeviceV1ShapeNResize = 19
	// resizing: the north-east corner is to be moved
	WpCursorShapeDeviceV1ShapeNeResize = 20
	// resizing: the north-west corner is to be moved
	WpCursorShapeDeviceV1ShapeNwResize = 21
	// resizing: the south border is to be moved
	WpCursorShapeDeviceV1ShapeSResize = 22
	// resizing: the south-east corner is to be moved
	WpCursorShapeDeviceV1ShapeSeResize = 23
	// resizing: the south-west corner is to be moved
	WpCursorShapeDeviceV1ShapeSwResize = 24
	// resizing: the west border is to be moved
	WpCursorShapeDeviceV1ShapeWResize = 25
	// resizing: the east and west borders are to be moved
	WpCursorShapeDeviceV1ShapeEwResize = 26
	// resizing: the north and south borders are to be moved
	WpCursorShapeDeviceV1ShapeNsResize = 27
	// resizing: the north-east and south-west corners are to be moved
	WpCursorShapeDeviceV1ShapeNeswResize = 28
	// resizing: the north-west and south-east corners are to be moved
	WpCursorShapeDeviceV1ShapeNwseResize = 29
	// resizing: that the item/column can be resized horizontally
	WpCursorShapeDeviceV1ShapeColResize = 30
	// resizing: that the item/row can be resized vertically
	WpCursorShapeDeviceV1ShapeRowResize = 31
	// something can be scrolled in any direction
	WpCursorShapeDeviceV1ShapeAllScroll = 32
	// something can be zoomed in
	WpCursorShapeDeviceV1ShapeZoomIn = 33
	// something can be zoomed out
	WpCursorShapeDeviceV1ShapeZoomOut = 34
	// drag-and-drop: the user will select which action will be carried out (non-css value)
	WpCursorShapeDeviceV1ShapeDndAsk = 35
	// resizing: something can be moved or resized in any direction (non-css value)
	WpCursorShapeDeviceV1ShapeAllResize = 36
)

// WpCursorShapeDeviceV1.error enum.
const (
	// the specified shape value is invalid
	WpCursorShapeDeviceV1ErrorInvalidShape = 1
)

// Destroy sends wp_cursor_shape_device_v1.destroy: destroy the cursor shape device.
// It destroys the proxy; do not use it afterwards.
func (px WpCursorShapeDeviceV1) Destroy() {
	px.marshal(0, nil, 0, marshalFlagDestroy)
}

// SetShape sends wp_cursor_shape_device_v1.set_shape: set device cursor to the shape.
func (px WpCursorShapeDeviceV1) SetShape(serial uint32, shape uint32) {
	px.marshal(1, nil, 0, 0, uintptr(serial), uintptr(shape))
}
