// Code generated by wlgen from fractional_scale_v1.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// WpFractionalScaleManagerV1 is wp_fractional_scale_manager_v1: fractional surface scale information.
type WpFractionalScaleManagerV1 struct{ Proxy }

// WpFractionalScaleManagerV1Interface is the wl_interface table for wp_fractional_scale_manager_v1.
var WpFractionalScaleManagerV1Interface Interface

// WpFractionalScaleManagerV1.error enum.
const (
	// the surface already has a fractional_scale object associated
	WpFractionalScaleManagerV1ErrorFractionalScaleExists = 0
)

// Destroy sends wp_fractional_scale_manager_v1.destroy: unbind the fractional surface scale interface.
// It destroys the proxy; do not use it afterwards.
func (px WpFractionalScaleManagerV1) Destroy() {
	px.marshal(0, nil, 0, marshalFlagDestroy)
}

// GetFractionalScale sends wp_fractional_scale_manager_v1.get_fractional_scale: extend surface interface for scale information.
func (px WpFractionalScaleManagerV1) GetFractionalScale(surface Surface) WpFractionalScaleV1 {
	ver := px.Version()
	r := px.marshal(1, &WpFractionalScaleV1Interface, ver, 0, 0, surface.ptr)
	return WpFractionalScaleV1{Proxy{ptr: r, ver: ver}}
}
