// Code generated by wlgen from fractional_scale_v1.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// WpFractionalScaleV1 is wp_fractional_scale_v1: fractional scale interface to a wl_surface.
type WpFractionalScaleV1 struct{ Proxy }

// WpFractionalScaleV1Interface is the wl_interface table for wp_fractional_scale_v1.
var WpFractionalScaleV1Interface Interface

// Destroy sends wp_fractional_scale_v1.destroy: remove surface scale information for surface.
// It destroys the proxy; do not use it afterwards.
func (px WpFractionalScaleV1) Destroy() {
	px.marshal(0, nil, 0, marshalFlagDestroy)
}

// WpFractionalScaleV1Handlers holds one func per wp_fractional_scale_v1 event. A nil func ignores the event.
// Strings and arrays are only valid until the func returns.
type WpFractionalScaleV1Handlers struct {
	// PreferredScale is wp_fractional_scale_v1.preferred_scale: notify of new preferred scale.
	PreferredScale func(scale uint32)
}

// SetHandlers routes the events of px to h, replacing any earlier handlers.
func (px WpFractionalScaleV1) SetHandlers(h WpFractionalScaleV1Handlers) {
	px.SetDispatcher(h.Dispatcher())
}

// WpFractionalScaleV1Dispatcher is the decoder for WpFractionalScaleV1Handlers, built once by Dispatcher
// and installed on any number of proxies without allocating.
type WpFractionalScaleV1Dispatcher struct {
	f func(opcode uint32, a *argSlots)
}

// SetDispatcher routes the events of px to d, replacing any earlier handlers.
func (px WpFractionalScaleV1) SetDispatcher(d WpFractionalScaleV1Dispatcher) { px.setDispatch(d.f) }

// Dispatcher builds the event decoder for h.
func (h WpFractionalScaleV1Handlers) Dispatcher() WpFractionalScaleV1Dispatcher {
	return WpFractionalScaleV1Dispatcher{func(opcode uint32, a *argSlots) {
		switch opcode {
		case 0:
			if h.PreferredScale != nil {
				h.PreferredScale(uint32(a[0]))
			}
		}
	}}
}
