// Code generated by wlgen from wp_primary_selection_unstable_v1.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

func defineWpPrimarySelectionUnstableV1() {
	defineInterface(&ZwpPrimarySelectionDeviceManagerV1Interface, "zwp_primary_selection_device_manager_v1", 1,
		[]message{
			newMessage("create_source", "n", []*Interface{&ZwpPrimarySelectionSourceV1Interface}),
			newMessage("get_device", "no", []*Interface{&ZwpPrimarySelectionDeviceV1Interface, &SeatInterface}),
			newMessage("destroy", "", nil),
		},
		nil,
	)
	defineInterface(&ZwpPrimarySelectionDeviceV1Interface, "zwp_primary_selection_device_v1", 1,
		[]message{
			newMessage("set_selection", "?ou", []*Interface{&ZwpPrimarySelectionSourceV1Interface, nil}),
			newMessage("destroy", "", nil),
		},
		[]message{
			newMessage("data_offer", "n", []*Interface{&ZwpPrimarySelectionOfferV1Interface}),
			newMessage("selection", "?o", []*Interface{&ZwpPrimarySelectionOfferV1Interface}),
		},
	)
	defineInterface(&ZwpPrimarySelectionOfferV1Interface, "zwp_primary_selection_offer_v1", 1,
		[]message{
			newMessage("receive", "sh", []*Interface{nil, nil}),
			newMessage("destroy", "", nil),
		},
		[]message{
			newMessage("offer", "s", []*Interface{nil}),
		},
	)
	defineInterface(&ZwpPrimarySelectionSourceV1Interface, "zwp_primary_selection_source_v1", 1,
		[]message{
			newMessage("offer", "s", []*Interface{nil}),
			newMessage("destroy", "", nil),
		},
		[]message{
			newMessage("send", "sh", []*Interface{nil, nil}),
			newMessage("cancelled", "", nil),
		},
	)
}
