// Code generated by wlgen from viewporter.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// WpViewport is wp_viewport: crop and scale interface to a wl_surface.
type WpViewport struct{ Proxy }

// WpViewportInterface is the wl_interface table for wp_viewport.
var WpViewportInterface Interface

// WpViewport.error enum.
const (
	// negative or zero values in width or height
	WpViewportErrorBadValue = 0
	// destination size is not integer
	WpViewportErrorBadSize = 1
	// source rectangle extends outside of the content area
	WpViewportErrorOutOfBuffer = 2
	// the wl_surface was destroyed
	WpViewportErrorNoSurface = 3
)

// Destroy sends wp_viewport.destroy: remove scaling and cropping from the surface.
// It destroys the proxy; do not use it afterwards.
func (px WpViewport) Destroy() {
	px.marshal(0, nil, 0, marshalFlagDestroy)
}

// SetSource sends wp_viewport.set_source: set the source rectangle for cropping.
func (px WpViewport) SetSource(x Fixed, y Fixed, width Fixed, height Fixed) {
	px.marshal(1, nil, 0, 0, uintptr(uint32(x)), uintptr(uint32(y)), uintptr(uint32(width)), uintptr(uint32(height)))
}

// SetDestination sends wp_viewport.set_destination: set the surface size for scaling.
func (px WpViewport) SetDestination(width int32, height int32) {
	px.marshal(2, nil, 0, 0, uintptr(uint32(width)), uintptr(uint32(height)))
}
