// Code generated by wlgen from viewporter.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// WpViewporter is wp_viewporter: surface cropping and scaling.
type WpViewporter struct{ Proxy }

// WpViewporterInterface is the wl_interface table for wp_viewporter.
var WpViewporterInterface Interface

// WpViewporter.error enum.
const (
	// the surface already has a viewport object associated
	WpViewporterErrorViewportExists = 0
)

// Destroy sends wp_viewporter.destroy: unbind from the cropping and scaling interface.
// It destroys the proxy; do not use it afterwards.
func (px WpViewporter) Destroy() {
	px.marshal(0, nil, 0, marshalFlagDestroy)
}

// GetViewport sends wp_viewporter.get_viewport: extend surface interface for crop and scale.
func (px WpViewporter) GetViewport(surface Surface) WpViewport {
	ver := px.Version()
	r := px.marshal(1, &WpViewportInterface, ver, 0, 0, surface.ptr)
	return WpViewport{Proxy{ptr: r, ver: ver}}
}
