// Code generated by wlgen from xdg_shell.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// XdgPositioner is xdg_positioner: child surface positioner.
type XdgPositioner struct{ Proxy }

// XdgPositionerInterface is the wl_interface table for xdg_positioner.
var XdgPositionerInterface Interface

// XdgPositioner.error enum.
const (
	// invalid input provided
	XdgPositionerErrorInvalidInput = 0
)

// XdgPositioner.anchor enum.
const (
	XdgPositionerAnchorNone        = 0
	XdgPositionerAnchorTop         = 1
	XdgPositionerAnchorBottom      = 2
	XdgPositionerAnchorLeft        = 3
	XdgPositionerAnchorRight       = 4
	XdgPositionerAnchorTopLeft     = 5
	XdgPositionerAnchorBottomLeft  = 6
	XdgPositionerAnchorTopRight    = 7
	XdgPositionerAnchorBottomRight = 8
)

// XdgPositioner.gravity enum.
const (
	XdgPositionerGravityNone        = 0
	XdgPositionerGravityTop         = 1
	XdgPositionerGravityBottom      = 2
	XdgPositionerGravityLeft        = 3
	XdgPositionerGravityRight       = 4
	XdgPositionerGravityTopLeft     = 5
	XdgPositionerGravityBottomLeft  = 6
	XdgPositionerGravityTopRight    = 7
	XdgPositionerGravityBottomRight = 8
)

// XdgPositioner.constraint_adjustment enum.
const (
	XdgPositionerConstraintAdjustmentNone    = 0
	XdgPositionerConstraintAdjustmentSlideX  = 1
	XdgPositionerConstraintAdjustmentSlideY  = 2
	XdgPositionerConstraintAdjustmentFlipX   = 4
	XdgPositionerConstraintAdjustmentFlipY   = 8
	XdgPositionerConstraintAdjustmentResizeX = 16
	XdgPositionerConstraintAdjustmentResizeY = 32
)

// Destroy sends xdg_positioner.destroy: destroy the xdg_positioner object.
// It destroys the proxy; do not use it afterwards.
func (px XdgPositioner) Destroy() {
	px.marshal(0, nil, 0, marshalFlagDestroy)
}

// SetSize sends xdg_positioner.set_size: set the size of the to-be positioned rectangle.
func (px XdgPositioner) SetSize(width int32, height int32) {
	px.marshal(1, nil, 0, 0, uintptr(uint32(width)), uintptr(uint32(height)))
}

// SetAnchorRect sends xdg_positioner.set_anchor_rect: set the anchor rectangle within the parent surface.
func (px XdgPositioner) SetAnchorRect(x int32, y int32, width int32, height int32) {
	px.marshal(2, nil, 0, 0, uintptr(uint32(x)), uintptr(uint32(y)), uintptr(uint32(width)), uintptr(uint32(height)))
}

// SetAnchor sends xdg_positioner.set_anchor: set anchor rectangle anchor.
func (px XdgPositioner) SetAnchor(anchor uint32) {
	px.marshal(3, nil, 0, 0, uintptr(anchor))
}

// SetGravity sends xdg_positioner.set_gravity: set child surface gravity.
func (px XdgPositioner) SetGravity(gravity uint32) {
	px.marshal(4, nil, 0, 0, uintptr(gravity))
}

// SetConstraintAdjustment sends xdg_positioner.set_constraint_adjustment: set the adjustment to be done when constrained.
func (px XdgPositioner) SetConstraintAdjustment(constraintAdjustment uint32) {
	px.marshal(5, nil, 0, 0, uintptr(constraintAdjustment))
}

// SetOffset sends xdg_positioner.set_offset: set surface position offset.
func (px XdgPositioner) SetOffset(x int32, y int32) {
	px.marshal(6, nil, 0, 0, uintptr(uint32(x)), uintptr(uint32(y)))
}

// SetReactive sends xdg_positioner.set_reactive: continuously reconstrain the surface.
// Needs version 3 of the bound object.
func (px XdgPositioner) SetReactive() {
	px.marshal(7, nil, 0, 0)
}

// SetParentSize sends xdg_positioner.set_parent_size.
// Needs version 3 of the bound object.
func (px XdgPositioner) SetParentSize(parentWidth int32, parentHeight int32) {
	px.marshal(8, nil, 0, 0, uintptr(uint32(parentWidth)), uintptr(uint32(parentHeight)))
}

// SetParentConfigure sends xdg_positioner.set_parent_configure: set parent configure this is a response to.
// Needs version 3 of the bound object.
func (px XdgPositioner) SetParentConfigure(serial uint32) {
	px.marshal(9, nil, 0, 0, uintptr(serial))
}
