// Code generated by wlgen from xdg_shell.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// XdgSurface is xdg_surface: desktop user interface surface base interface.
type XdgSurface struct{ Proxy }

// XdgSurfaceInterface is the wl_interface table for xdg_surface.
var XdgSurfaceInterface Interface

// XdgSurface.error enum.
const (
	// Surface was not fully constructed
	XdgSurfaceErrorNotConstructed = 1
	// Surface was already constructed
	XdgSurfaceErrorAlreadyConstructed = 2
	// Attaching a buffer to an unconfigured surface
	XdgSurfaceErrorUnconfiguredBuffer = 3
	// Invalid serial number when acking a configure event
	XdgSurfaceErrorInvalidSerial = 4
	// Width or height was zero or negative
	XdgSurfaceErrorInvalidSize = 5
	// Surface was destroyed before its role object
	XdgSurfaceErrorDefunctRoleObject = 6
)

// Destroy sends xdg_surface.destroy: destroy the xdg_surface.
// It destroys the proxy; do not use it afterwards.
func (px XdgSurface) Destroy() {
	px.marshal(0, nil, 0, marshalFlagDestroy)
}

// GetToplevel sends xdg_surface.get_toplevel: assign the xdg_toplevel surface role.
func (px XdgSurface) GetToplevel() XdgToplevel {
	ver := px.Version()
	r := px.marshal(1, &XdgToplevelInterface, ver, 0, 0)
	return XdgToplevel{Proxy{ptr: r, ver: ver}}
}

// GetPopup sends xdg_surface.get_popup: assign the xdg_popup surface role.
func (px XdgSurface) GetPopup(parent XdgSurface, positioner XdgPositioner) XdgPopup {
	ver := px.Version()
	r := px.marshal(2, &XdgPopupInterface, ver, 0, 0, parent.ptr, positioner.ptr)
	return XdgPopup{Proxy{ptr: r, ver: ver}}
}

// SetWindowGeometry sends xdg_surface.set_window_geometry: set the new window geometry.
func (px XdgSurface) SetWindowGeometry(x int32, y int32, width int32, height int32) {
	px.marshal(3, nil, 0, 0, uintptr(uint32(x)), uintptr(uint32(y)), uintptr(uint32(width)), uintptr(uint32(height)))
}

// AckConfigure sends xdg_surface.ack_configure: ack a configure event.
func (px XdgSurface) AckConfigure(serial uint32) {
	px.marshal(4, nil, 0, 0, uintptr(serial))
}

// XdgSurfaceHandlers holds one func per xdg_surface event. A nil func ignores the event.
// Strings and arrays are only valid until the func returns.
type XdgSurfaceHandlers struct {
	// Configure is xdg_surface.configure: suggest a surface change.
	Configure func(serial uint32)
}

// SetHandlers routes the events of px to h, replacing any earlier handlers.
func (px XdgSurface) SetHandlers(h XdgSurfaceHandlers) { px.SetDispatcher(h.Dispatcher()) }

// XdgSurfaceDispatcher is the decoder for XdgSurfaceHandlers, built once by Dispatcher
// and installed on any number of proxies without allocating.
type XdgSurfaceDispatcher struct {
	f func(opcode uint32, a *argSlots)
}

// SetDispatcher routes the events of px to d, replacing any earlier handlers.
func (px XdgSurface) SetDispatcher(d XdgSurfaceDispatcher) { px.setDispatch(d.f) }

// Dispatcher builds the event decoder for h.
func (h XdgSurfaceHandlers) Dispatcher() XdgSurfaceDispatcher {
	return XdgSurfaceDispatcher{func(opcode uint32, a *argSlots) {
		switch opcode {
		case 0:
			if h.Configure != nil {
				h.Configure(uint32(a[0]))
			}
		}
	}}
}
