// Code generated by wlgen from xdg_shell.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// XdgPopup is xdg_popup: short-lived, popup surfaces for menus.
type XdgPopup struct{ Proxy }

// XdgPopupInterface is the wl_interface table for xdg_popup.
var XdgPopupInterface Interface

// XdgPopup.error enum.
const (
	// tried to grab after being mapped
	XdgPopupErrorInvalidGrab = 0
)

// Destroy sends xdg_popup.destroy: remove xdg_popup interface.
// It destroys the proxy; do not use it afterwards.
func (px XdgPopup) Destroy() {
	px.marshal(0, nil, 0, marshalFlagDestroy)
}

// Grab sends xdg_popup.grab: make the popup take an explicit grab.
func (px XdgPopup) Grab(seat Seat, serial uint32) {
	px.marshal(1, nil, 0, 0, seat.ptr, uintptr(serial))
}

// Reposition sends xdg_popup.reposition: recalculate the popup's location.
// Needs version 3 of the bound object.
func (px XdgPopup) Reposition(positioner XdgPositioner, token uint32) {
	px.marshal(2, nil, 0, 0, positioner.ptr, uintptr(token))
}

// XdgPopupHandlers holds one func per xdg_popup event. A nil func ignores the event.
// Strings and arrays are only valid until the func returns.
type XdgPopupHandlers struct {
	// Configure is xdg_popup.configure: configure the popup surface.
	Configure func(x int32, y int32, width int32, height int32)
	// PopupDone is xdg_popup.popup_done: popup interaction is done.
	PopupDone func()
	// Repositioned is xdg_popup.repositioned: signal the completion of a repositioned request.
	Repositioned func(token uint32)
}

// SetHandlers routes the events of px to h, replacing any earlier handlers.
func (px XdgPopup) SetHandlers(h XdgPopupHandlers) {
	px.setDispatch(func(opcode uint32, a *argSlots) {
		switch opcode {
		case 0:
			if h.Configure != nil {
				h.Configure(int32(uint32(a[0])), int32(uint32(a[1])), int32(uint32(a[2])), int32(uint32(a[3])))
			}
		case 1:
			if h.PopupDone != nil {
				h.PopupDone()
			}
		case 2:
			if h.Repositioned != nil {
				h.Repositioned(uint32(a[0]))
			}
		}
	})
}
