// Code generated by wlgen from xdg_shell.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// XdgToplevel is xdg_toplevel: toplevel surface.
type XdgToplevel struct{ Proxy }

// XdgToplevelInterface is the wl_interface table for xdg_toplevel.
var XdgToplevelInterface Interface

// XdgToplevel.error enum.
const (
	// provided value is not a valid variant of the resize_edge enum
	XdgToplevelErrorInvalidResizeEdge = 0
	// invalid parent toplevel
	XdgToplevelErrorInvalidParent = 1
	// client provided an invalid min or max size
	XdgToplevelErrorInvalidSize = 2
)

// XdgToplevel.resize_edge enum.
const (
	XdgToplevelResizeEdgeNone        = 0
	XdgToplevelResizeEdgeTop         = 1
	XdgToplevelResizeEdgeBottom      = 2
	XdgToplevelResizeEdgeLeft        = 4
	XdgToplevelResizeEdgeTopLeft     = 5
	XdgToplevelResizeEdgeBottomLeft  = 6
	XdgToplevelResizeEdgeRight       = 8
	XdgToplevelResizeEdgeTopRight    = 9
	XdgToplevelResizeEdgeBottomRight = 10
)

// XdgToplevel.state enum.
const (
	// the surface is maximized
	XdgToplevelStateMaximized = 1
	// the surface is fullscreen
	XdgToplevelStateFullscreen = 2
	// the surface is being resized
	XdgToplevelStateResizing = 3
	// the surface is now activated
	XdgToplevelStateActivated         = 4
	XdgToplevelStateTiledLeft         = 5
	XdgToplevelStateTiledRight        = 6
	XdgToplevelStateTiledTop          = 7
	XdgToplevelStateTiledBottom       = 8
	XdgToplevelStateSuspended         = 9
	XdgToplevelStateConstrainedLeft   = 10
	XdgToplevelStateConstrainedRight  = 11
	XdgToplevelStateConstrainedTop    = 12
	XdgToplevelStateConstrainedBottom = 13
)

// XdgToplevel.wm_capabilities enum.
const (
	// show_window_menu is available
	XdgToplevelWmCapabilitiesWindowMenu = 1
	// set_maximized and unset_maximized are available
	XdgToplevelWmCapabilitiesMaximize = 2
	// set_fullscreen and unset_fullscreen are available
	XdgToplevelWmCapabilitiesFullscreen = 3
	// set_minimized is available
	XdgToplevelWmCapabilitiesMinimize = 4
)

// Destroy sends xdg_toplevel.destroy: destroy the xdg_toplevel.
// It destroys the proxy; do not use it afterwards.
func (px XdgToplevel) Destroy() {
	px.marshal(0, nil, 0, marshalFlagDestroy)
}

// SetParent sends xdg_toplevel.set_parent: set the parent of this surface.
func (px XdgToplevel) SetParent(parent XdgToplevel) {
	px.marshal(1, nil, 0, 0, parent.ptr)
}

// SetTitle sends xdg_toplevel.set_title: set surface title.
func (px XdgToplevel) SetTitle(title string) {
	titleC := cString(title, false)
	px.marshal(2, nil, 0, 0, cStringPtr(titleC))
	runtime.KeepAlive(titleC)
}

// SetAppId sends xdg_toplevel.set_app_id: set application ID.
func (px XdgToplevel) SetAppId(appId string) {
	appIdC := cString(appId, false)
	px.marshal(3, nil, 0, 0, cStringPtr(appIdC))
	runtime.KeepAlive(appIdC)
}

// ShowWindowMenu sends xdg_toplevel.show_window_menu: show the window menu.
func (px XdgToplevel) ShowWindowMenu(seat Seat, serial uint32, x int32, y int32) {
	px.marshal(4, nil, 0, 0, seat.ptr, uintptr(serial), uintptr(uint32(x)), uintptr(uint32(y)))
}

// Move sends xdg_toplevel.move: start an interactive move.
func (px XdgToplevel) Move(seat Seat, serial uint32) {
	px.marshal(5, nil, 0, 0, seat.ptr, uintptr(serial))
}

// Resize sends xdg_toplevel.resize: start an interactive resize.
func (px XdgToplevel) Resize(seat Seat, serial uint32, edges uint32) {
	px.marshal(6, nil, 0, 0, seat.ptr, uintptr(serial), uintptr(edges))
}

// SetMaxSize sends xdg_toplevel.set_max_size: set the maximum size.
func (px XdgToplevel) SetMaxSize(width int32, height int32) {
	px.marshal(7, nil, 0, 0, uintptr(uint32(width)), uintptr(uint32(height)))
}

// SetMinSize sends xdg_toplevel.set_min_size: set the minimum size.
func (px XdgToplevel) SetMinSize(width int32, height int32) {
	px.marshal(8, nil, 0, 0, uintptr(uint32(width)), uintptr(uint32(height)))
}

// SetMaximized sends xdg_toplevel.set_maximized: maximize the window.
func (px XdgToplevel) SetMaximized() {
	px.marshal(9, nil, 0, 0)
}

// UnsetMaximized sends xdg_toplevel.unset_maximized: unmaximize the window.
func (px XdgToplevel) UnsetMaximized() {
	px.marshal(10, nil, 0, 0)
}

// SetFullscreen sends xdg_toplevel.set_fullscreen: set the window as fullscreen on an output.
func (px XdgToplevel) SetFullscreen(output Output) {
	px.marshal(11, nil, 0, 0, output.ptr)
}

// UnsetFullscreen sends xdg_toplevel.unset_fullscreen: unset the window as fullscreen.
func (px XdgToplevel) UnsetFullscreen() {
	px.marshal(12, nil, 0, 0)
}

// SetMinimized sends xdg_toplevel.set_minimized: set the window as minimized.
func (px XdgToplevel) SetMinimized() {
	px.marshal(13, nil, 0, 0)
}

// XdgToplevelHandlers holds one func per xdg_toplevel event. A nil func ignores the event.
// Strings and arrays are only valid until the func returns.
type XdgToplevelHandlers struct {
	// Configure is xdg_toplevel.configure: suggest a surface change.
	Configure func(width int32, height int32, states []byte)
	// Close is xdg_toplevel.close: surface wants to be closed.
	Close func()
	// ConfigureBounds is xdg_toplevel.configure_bounds: recommended window geometry bounds.
	ConfigureBounds func(width int32, height int32)
	// WmCapabilities is xdg_toplevel.wm_capabilities: compositor capabilities.
	WmCapabilities func(capabilities []byte)
}

// SetHandlers routes the events of px to h, replacing any earlier handlers.
func (px XdgToplevel) SetHandlers(h XdgToplevelHandlers) { px.SetDispatcher(h.Dispatcher()) }

// XdgToplevelDispatcher is the decoder for XdgToplevelHandlers, built once by Dispatcher
// and installed on any number of proxies without allocating.
type XdgToplevelDispatcher struct {
	f func(opcode uint32, a *argSlots)
}

// SetDispatcher routes the events of px to d, replacing any earlier handlers.
func (px XdgToplevel) SetDispatcher(d XdgToplevelDispatcher) { px.setDispatch(d.f) }

// Dispatcher builds the event decoder for h.
func (h XdgToplevelHandlers) Dispatcher() XdgToplevelDispatcher {
	return XdgToplevelDispatcher{func(opcode uint32, a *argSlots) {
		switch opcode {
		case 0:
			if h.Configure != nil {
				h.Configure(int32(uint32(a[0])), int32(uint32(a[1])), arrayBytes(a[2]))
			}
		case 1:
			if h.Close != nil {
				h.Close()
			}
		case 2:
			if h.ConfigureBounds != nil {
				h.ConfigureBounds(int32(uint32(a[0])), int32(uint32(a[1])))
			}
		case 3:
			if h.WmCapabilities != nil {
				h.WmCapabilities(arrayBytes(a[0]))
			}
		}
	}}
}
