// Code generated by wlgen from xdg_decoration_unstable_v1.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

func defineXdgDecorationUnstableV1() {
	defineInterface(&ZxdgDecorationManagerV1Interface, "zxdg_decoration_manager_v1", 1,
		[]message{
			newMessage("destroy", "", nil),
			newMessage("get_toplevel_decoration", "no", []*Interface{&ZxdgToplevelDecorationV1Interface, &XdgToplevelInterface}),
		},
		nil,
	)
	defineInterface(&ZxdgToplevelDecorationV1Interface, "zxdg_toplevel_decoration_v1", 1,
		[]message{
			newMessage("destroy", "", nil),
			newMessage("set_mode", "u", []*Interface{nil}),
			newMessage("unset_mode", "", nil),
		},
		[]message{
			newMessage("configure", "u", []*Interface{nil}),
		},
	)
}
