// Code generated by wlgen from xdg_shell.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

func defineXdgShell() {
	defineInterface(&XdgWmBaseInterface, "xdg_wm_base", 7,
		[]message{
			newMessage("destroy", "", nil),
			newMessage("create_positioner", "n", []*Interface{&XdgPositionerInterface}),
			newMessage("get_xdg_surface", "no", []*Interface{&XdgSurfaceInterface, &SurfaceInterface}),
			newMessage("pong", "u", []*Interface{nil}),
		},
		[]message{
			newMessage("ping", "u", []*Interface{nil}),
		},
	)
	defineInterface(&XdgPositionerInterface, "xdg_positioner", 7,
		[]message{
			newMessage("destroy", "", nil),
			newMessage("set_size", "ii", []*Interface{nil, nil}),
			newMessage("set_anchor_rect", "iiii", []*Interface{nil, nil, nil, nil}),
			newMessage("set_anchor", "u", []*Interface{nil}),
			newMessage("set_gravity", "u", []*Interface{nil}),
			newMessage("set_constraint_adjustment", "u", []*Interface{nil}),
			newMessage("set_offset", "ii", []*Interface{nil, nil}),
			newMessage("set_reactive", "3", nil),
			newMessage("set_parent_size", "3ii", []*Interface{nil, nil}),
			newMessage("set_parent_configure", "3u", []*Interface{nil}),
		},
		nil,
	)
	defineInterface(&XdgSurfaceInterface, "xdg_surface", 7,
		[]message{
			newMessage("destroy", "", nil),
			newMessage("get_toplevel", "n", []*Interface{&XdgToplevelInterface}),
			newMessage("get_popup", "n?oo", []*Interface{&XdgPopupInterface, &XdgSurfaceInterface, &XdgPositionerInterface}),
			newMessage("set_window_geometry", "iiii", []*Interface{nil, nil, nil, nil}),
			newMessage("ack_configure", "u", []*Interface{nil}),
		},
		[]message{
			newMessage("configure", "u", []*Interface{nil}),
		},
	)
	defineInterface(&XdgToplevelInterface, "xdg_toplevel", 7,
		[]message{
			newMessage("destroy", "", nil),
			newMessage("set_parent", "?o", []*Interface{&XdgToplevelInterface}),
			newMessage("set_title", "s", []*Interface{nil}),
			newMessage("set_app_id", "s", []*Interface{nil}),
			newMessage("show_window_menu", "ouii", []*Interface{&SeatInterface, nil, nil, nil}),
			newMessage("move", "ou", []*Interface{&SeatInterface, nil}),
			newMessage("resize", "ouu", []*Interface{&SeatInterface, nil, nil}),
			newMessage("set_max_size", "ii", []*Interface{nil, nil}),
			newMessage("set_min_size", "ii", []*Interface{nil, nil}),
			newMessage("set_maximized", "", nil),
			newMessage("unset_maximized", "", nil),
			newMessage("set_fullscreen", "?o", []*Interface{&OutputInterface}),
			newMessage("unset_fullscreen", "", nil),
			newMessage("set_minimized", "", nil),
		},
		[]message{
			newMessage("configure", "iia", []*Interface{nil, nil, nil}),
			newMessage("close", "", nil),
			newMessage("configure_bounds", "4ii", []*Interface{nil, nil}),
			newMessage("wm_capabilities", "5a", []*Interface{nil}),
		},
	)
	defineInterface(&XdgPopupInterface, "xdg_popup", 7,
		[]message{
			newMessage("destroy", "", nil),
			newMessage("grab", "ou", []*Interface{&SeatInterface, nil}),
			newMessage("reposition", "3ou", []*Interface{&XdgPositionerInterface, nil}),
		},
		[]message{
			newMessage("configure", "iiii", []*Interface{nil, nil, nil, nil}),
			newMessage("popup_done", "", nil),
			newMessage("repositioned", "3u", []*Interface{nil}),
		},
	)
}
