// Code generated by wlgen from xdg_shell.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// XdgWmBase is xdg_wm_base: create desktop-style surfaces.
type XdgWmBase struct{ Proxy }

// XdgWmBaseInterface is the wl_interface table for xdg_wm_base.
var XdgWmBaseInterface Interface

// XdgWmBase.error enum.
const (
	// given wl_surface has another role
	XdgWmBaseErrorRole = 0
	// xdg_wm_base was destroyed before children
	XdgWmBaseErrorDefunctSurfaces = 1
	// the client tried to map or destroy a non-topmost popup
	XdgWmBaseErrorNotTheTopmostPopup = 2
	// the client specified an invalid popup parent surface
	XdgWmBaseErrorInvalidPopupParent = 3
	// the client provided an invalid surface state
	XdgWmBaseErrorInvalidSurfaceState = 4
	// the client provided an invalid positioner
	XdgWmBaseErrorInvalidPositioner = 5
	// the client didn’t respond to a ping event in time
	XdgWmBaseErrorUnresponsive = 6
)

// Destroy sends xdg_wm_base.destroy: destroy xdg_wm_base.
// It destroys the proxy; do not use it afterwards.
func (px XdgWmBase) Destroy() {
	px.marshal(0, nil, 0, marshalFlagDestroy)
}

// CreatePositioner sends xdg_wm_base.create_positioner: create a positioner object.
func (px XdgWmBase) CreatePositioner() XdgPositioner {
	ver := px.Version()
	r := px.marshal(1, &XdgPositionerInterface, ver, 0, 0)
	return XdgPositioner{Proxy{ptr: r, ver: ver}}
}

// GetXdgSurface sends xdg_wm_base.get_xdg_surface: create a shell surface from a surface.
func (px XdgWmBase) GetXdgSurface(surface Surface) XdgSurface {
	ver := px.Version()
	r := px.marshal(2, &XdgSurfaceInterface, ver, 0, 0, surface.ptr)
	return XdgSurface{Proxy{ptr: r, ver: ver}}
}

// Pong sends xdg_wm_base.pong: respond to a ping event.
func (px XdgWmBase) Pong(serial uint32) {
	px.marshal(3, nil, 0, 0, uintptr(serial))
}

// XdgWmBaseHandlers holds one func per xdg_wm_base event. A nil func ignores the event.
// Strings and arrays are only valid until the func returns.
type XdgWmBaseHandlers struct {
	// Ping is xdg_wm_base.ping: check if the client is alive.
	Ping func(serial uint32)
}

// SetHandlers routes the events of px to h, replacing any earlier handlers.
func (px XdgWmBase) SetHandlers(h XdgWmBaseHandlers) {
	px.setDispatch(func(opcode uint32, a *argSlots) {
		switch opcode {
		case 0:
			if h.Ping != nil {
				h.Ping(uint32(a[0]))
			}
		}
	})
}
