// Code generated by wlgen from wlr_virtual_pointer_unstable_v1.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// ZwlrVirtualPointerV1 is zwlr_virtual_pointer_v1: virtual pointer.
type ZwlrVirtualPointerV1 struct{ Proxy }

// ZwlrVirtualPointerV1Interface is the wl_interface table for zwlr_virtual_pointer_v1.
var ZwlrVirtualPointerV1Interface Interface

// ZwlrVirtualPointerV1.error enum.
const (
	// client sent invalid axis enumeration value
	ZwlrVirtualPointerV1ErrorInvalidAxis = 0
	// client sent invalid axis source enumeration value
	ZwlrVirtualPointerV1ErrorInvalidAxisSource = 1
)

// Motion sends zwlr_virtual_pointer_v1.motion: pointer relative motion event.
func (px ZwlrVirtualPointerV1) Motion(time uint32, dx Fixed, dy Fixed) {
	px.marshal(0, nil, 0, 0, uintptr(time), uintptr(uint32(dx)), uintptr(uint32(dy)))
}

// MotionAbsolute sends zwlr_virtual_pointer_v1.motion_absolute: pointer absolute motion event.
func (px ZwlrVirtualPointerV1) MotionAbsolute(time uint32, x uint32, y uint32, xExtent uint32, yExtent uint32) {
	px.marshal(1, nil, 0, 0, uintptr(time), uintptr(x), uintptr(y), uintptr(xExtent), uintptr(yExtent))
}

// Button sends zwlr_virtual_pointer_v1.button: button event.
func (px ZwlrVirtualPointerV1) Button(time uint32, button uint32, state uint32) {
	px.marshal(2, nil, 0, 0, uintptr(time), uintptr(button), uintptr(state))
}

// Axis sends zwlr_virtual_pointer_v1.axis: axis event.
func (px ZwlrVirtualPointerV1) Axis(time uint32, axis uint32, value Fixed) {
	px.marshal(3, nil, 0, 0, uintptr(time), uintptr(axis), uintptr(uint32(value)))
}

// Frame sends zwlr_virtual_pointer_v1.frame: end of a pointer event sequence.
func (px ZwlrVirtualPointerV1) Frame() {
	px.marshal(4, nil, 0, 0)
}

// AxisSource sends zwlr_virtual_pointer_v1.axis_source: axis source event.
func (px ZwlrVirtualPointerV1) AxisSource(axisSource uint32) {
	px.marshal(5, nil, 0, 0, uintptr(axisSource))
}

// AxisStop sends zwlr_virtual_pointer_v1.axis_stop: axis stop event.
func (px ZwlrVirtualPointerV1) AxisStop(time uint32, axis uint32) {
	px.marshal(6, nil, 0, 0, uintptr(time), uintptr(axis))
}

// AxisDiscrete sends zwlr_virtual_pointer_v1.axis_discrete: axis click event.
func (px ZwlrVirtualPointerV1) AxisDiscrete(time uint32, axis uint32, value Fixed, discrete int32) {
	px.marshal(7, nil, 0, 0, uintptr(time), uintptr(axis), uintptr(uint32(value)), uintptr(uint32(discrete)))
}

// Destroy sends zwlr_virtual_pointer_v1.destroy: destroy the virtual pointer object.
// It destroys the proxy; do not use it afterwards.
func (px ZwlrVirtualPointerV1) Destroy() {
	px.marshal(8, nil, 0, marshalFlagDestroy)
}
