// Code generated by wlgen from wlr_virtual_pointer_unstable_v1.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// ZwlrVirtualPointerManagerV1 is zwlr_virtual_pointer_manager_v1: virtual pointer manager.
type ZwlrVirtualPointerManagerV1 struct{ Proxy }

// ZwlrVirtualPointerManagerV1Interface is the wl_interface table for zwlr_virtual_pointer_manager_v1.
var ZwlrVirtualPointerManagerV1Interface Interface

// CreateVirtualPointer sends zwlr_virtual_pointer_manager_v1.create_virtual_pointer: Create a new virtual pointer.
func (px ZwlrVirtualPointerManagerV1) CreateVirtualPointer(seat Seat) ZwlrVirtualPointerV1 {
	ver := px.Version()
	r := px.marshal(0, &ZwlrVirtualPointerV1Interface, ver, 0, seat.ptr, 0)
	return ZwlrVirtualPointerV1{Proxy{ptr: r, ver: ver}}
}

// Destroy sends zwlr_virtual_pointer_manager_v1.destroy: destroy the virtual pointer manager.
// It destroys the proxy; do not use it afterwards.
func (px ZwlrVirtualPointerManagerV1) Destroy() {
	px.marshal(1, nil, 0, marshalFlagDestroy)
}

// CreateVirtualPointerWithOutput sends zwlr_virtual_pointer_manager_v1.create_virtual_pointer_with_output: Create a new virtual pointer.
// Needs version 2 of the bound object.
func (px ZwlrVirtualPointerManagerV1) CreateVirtualPointerWithOutput(seat Seat, output Output) ZwlrVirtualPointerV1 {
	ver := px.Version()
	r := px.marshal(2, &ZwlrVirtualPointerV1Interface, ver, 0, seat.ptr, output.ptr, 0)
	return ZwlrVirtualPointerV1{Proxy{ptr: r, ver: ver}}
}
