// Code generated by wlgen from wp_primary_selection_unstable_v1.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// ZwpPrimarySelectionSourceV1 is zwp_primary_selection_source_v1: offer to replace the contents of the primary selection.
type ZwpPrimarySelectionSourceV1 struct{ Proxy }

// ZwpPrimarySelectionSourceV1Interface is the wl_interface table for zwp_primary_selection_source_v1.
var ZwpPrimarySelectionSourceV1Interface Interface

// Offer sends zwp_primary_selection_source_v1.offer: add an offered mime type.
func (px ZwpPrimarySelectionSourceV1) Offer(mimeType string) {
	mimeTypeC := cString(mimeType, false)
	px.marshal(0, nil, 0, 0, cStringPtr(mimeTypeC))
	runtime.KeepAlive(mimeTypeC)
}

// Destroy sends zwp_primary_selection_source_v1.destroy: destroy the primary selection source.
// It destroys the proxy; do not use it afterwards.
func (px ZwpPrimarySelectionSourceV1) Destroy() {
	px.marshal(1, nil, 0, marshalFlagDestroy)
}

// ZwpPrimarySelectionSourceV1Handlers holds one func per zwp_primary_selection_source_v1 event. A nil func ignores the event.
// Strings and arrays are only valid until the func returns.
type ZwpPrimarySelectionSourceV1Handlers struct {
	// Send is zwp_primary_selection_source_v1.send: send the primary selection contents.
	Send func(mimeType string, fd int)
	// Cancelled is zwp_primary_selection_source_v1.cancelled: request for primary selection contents was canceled.
	Cancelled func()
}

// SetHandlers routes the events of px to h, replacing any earlier handlers.
func (px ZwpPrimarySelectionSourceV1) SetHandlers(h ZwpPrimarySelectionSourceV1Handlers) {
	px.SetDispatcher(h.Dispatcher())
}

// ZwpPrimarySelectionSourceV1Dispatcher is the decoder for ZwpPrimarySelectionSourceV1Handlers, built once by Dispatcher
// and installed on any number of proxies without allocating.
type ZwpPrimarySelectionSourceV1Dispatcher struct {
	f func(opcode uint32, a *argSlots)
}

// SetDispatcher routes the events of px to d, replacing any earlier handlers.
func (px ZwpPrimarySelectionSourceV1) SetDispatcher(d ZwpPrimarySelectionSourceV1Dispatcher) {
	px.setDispatch(d.f)
}

// Dispatcher builds the event decoder for h.
func (h ZwpPrimarySelectionSourceV1Handlers) Dispatcher() ZwpPrimarySelectionSourceV1Dispatcher {
	return ZwpPrimarySelectionSourceV1Dispatcher{func(opcode uint32, a *argSlots) {
		switch opcode {
		case 0:
			if h.Send != nil {
				h.Send(goString(a[0]), int(int32(uint32(a[1]))))
			}
		case 1:
			if h.Cancelled != nil {
				h.Cancelled()
			}
		}
	}}
}
