// Code generated by wlgen from wp_primary_selection_unstable_v1.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// ZwpPrimarySelectionDeviceV1 is zwp_primary_selection_device_v1: .
type ZwpPrimarySelectionDeviceV1 struct{ Proxy }

// ZwpPrimarySelectionDeviceV1Interface is the wl_interface table for zwp_primary_selection_device_v1.
var ZwpPrimarySelectionDeviceV1Interface Interface

// SetSelection sends zwp_primary_selection_device_v1.set_selection: set the primary selection.
func (px ZwpPrimarySelectionDeviceV1) SetSelection(source ZwpPrimarySelectionSourceV1, serial uint32) {
	px.marshal(0, nil, 0, 0, source.ptr, uintptr(serial))
}

// Destroy sends zwp_primary_selection_device_v1.destroy: destroy the primary selection device.
// It destroys the proxy; do not use it afterwards.
func (px ZwpPrimarySelectionDeviceV1) Destroy() {
	px.marshal(1, nil, 0, marshalFlagDestroy)
}

// ZwpPrimarySelectionDeviceV1Handlers holds one func per zwp_primary_selection_device_v1 event. A nil func ignores the event.
// Strings and arrays are only valid until the func returns.
type ZwpPrimarySelectionDeviceV1Handlers struct {
	// DataOffer is zwp_primary_selection_device_v1.data_offer: introduce a new wp_primary_selection_offer.
	DataOffer func(offer ZwpPrimarySelectionOfferV1)
	// Selection is zwp_primary_selection_device_v1.selection: advertise a new primary selection.
	Selection func(id ZwpPrimarySelectionOfferV1)
}

// SetHandlers routes the events of px to h, replacing any earlier handlers.
func (px ZwpPrimarySelectionDeviceV1) SetHandlers(h ZwpPrimarySelectionDeviceV1Handlers) {
	px.SetDispatcher(h.Dispatcher())
}

// ZwpPrimarySelectionDeviceV1Dispatcher is the decoder for ZwpPrimarySelectionDeviceV1Handlers, built once by Dispatcher
// and installed on any number of proxies without allocating.
type ZwpPrimarySelectionDeviceV1Dispatcher struct {
	f func(opcode uint32, a *argSlots)
}

// SetDispatcher routes the events of px to d, replacing any earlier handlers.
func (px ZwpPrimarySelectionDeviceV1) SetDispatcher(d ZwpPrimarySelectionDeviceV1Dispatcher) {
	px.setDispatch(d.f)
}

// Dispatcher builds the event decoder for h.
func (h ZwpPrimarySelectionDeviceV1Handlers) Dispatcher() ZwpPrimarySelectionDeviceV1Dispatcher {
	return ZwpPrimarySelectionDeviceV1Dispatcher{func(opcode uint32, a *argSlots) {
		switch opcode {
		case 0:
			if h.DataOffer != nil {
				h.DataOffer(ZwpPrimarySelectionOfferV1{Proxy{ptr: a[0]}})
			}
		case 1:
			if h.Selection != nil {
				h.Selection(ZwpPrimarySelectionOfferV1{Proxy{ptr: a[0]}})
			}
		}
	}}
}
