// Code generated by wlgen from wp_primary_selection_unstable_v1.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// ZwpPrimarySelectionDeviceManagerV1 is zwp_primary_selection_device_manager_v1: X primary selection emulation.
type ZwpPrimarySelectionDeviceManagerV1 struct{ Proxy }

// ZwpPrimarySelectionDeviceManagerV1Interface is the wl_interface table for zwp_primary_selection_device_manager_v1.
var ZwpPrimarySelectionDeviceManagerV1Interface Interface

// CreateSource sends zwp_primary_selection_device_manager_v1.create_source: create a new primary selection source.
func (px ZwpPrimarySelectionDeviceManagerV1) CreateSource() ZwpPrimarySelectionSourceV1 {
	ver := px.Version()
	r := px.marshal(0, &ZwpPrimarySelectionSourceV1Interface, ver, 0, 0)
	return ZwpPrimarySelectionSourceV1{Proxy{ptr: r, ver: ver}}
}

// GetDevice sends zwp_primary_selection_device_manager_v1.get_device: create a new primary selection device.
func (px ZwpPrimarySelectionDeviceManagerV1) GetDevice(seat Seat) ZwpPrimarySelectionDeviceV1 {
	ver := px.Version()
	r := px.marshal(1, &ZwpPrimarySelectionDeviceV1Interface, ver, 0, 0, seat.ptr)
	return ZwpPrimarySelectionDeviceV1{Proxy{ptr: r, ver: ver}}
}

// Destroy sends zwp_primary_selection_device_manager_v1.destroy: destroy the primary selection device manager.
// It destroys the proxy; do not use it afterwards.
func (px ZwpPrimarySelectionDeviceManagerV1) Destroy() {
	px.marshal(2, nil, 0, marshalFlagDestroy)
}
