// Code generated by wlgen from wp_primary_selection_unstable_v1.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// ZwpPrimarySelectionOfferV1 is zwp_primary_selection_offer_v1: offer to transfer primary selection contents.
type ZwpPrimarySelectionOfferV1 struct{ Proxy }

// ZwpPrimarySelectionOfferV1Interface is the wl_interface table for zwp_primary_selection_offer_v1.
var ZwpPrimarySelectionOfferV1Interface Interface

// Receive sends zwp_primary_selection_offer_v1.receive: request that the data is transferred.
func (px ZwpPrimarySelectionOfferV1) Receive(mimeType string, fd int) {
	mimeTypeC := cString(mimeType, false)
	px.marshal(0, nil, 0, 0, cStringPtr(mimeTypeC), uintptr(fd))
	runtime.KeepAlive(mimeTypeC)
}

// Destroy sends zwp_primary_selection_offer_v1.destroy: destroy the primary selection offer.
// It destroys the proxy; do not use it afterwards.
func (px ZwpPrimarySelectionOfferV1) Destroy() {
	px.marshal(1, nil, 0, marshalFlagDestroy)
}

// ZwpPrimarySelectionOfferV1Handlers holds one func per zwp_primary_selection_offer_v1 event. A nil func ignores the event.
// Strings and arrays are only valid until the func returns.
type ZwpPrimarySelectionOfferV1Handlers struct {
	// Offer is zwp_primary_selection_offer_v1.offer: advertise offered mime type.
	Offer func(mimeType string)
}

// SetHandlers routes the events of px to h, replacing any earlier handlers.
func (px ZwpPrimarySelectionOfferV1) SetHandlers(h ZwpPrimarySelectionOfferV1Handlers) {
	px.SetDispatcher(h.Dispatcher())
}

// ZwpPrimarySelectionOfferV1Dispatcher is the decoder for ZwpPrimarySelectionOfferV1Handlers, built once by Dispatcher
// and installed on any number of proxies without allocating.
type ZwpPrimarySelectionOfferV1Dispatcher struct {
	f func(opcode uint32, a *argSlots)
}

// SetDispatcher routes the events of px to d, replacing any earlier handlers.
func (px ZwpPrimarySelectionOfferV1) SetDispatcher(d ZwpPrimarySelectionOfferV1Dispatcher) {
	px.setDispatch(d.f)
}

// Dispatcher builds the event decoder for h.
func (h ZwpPrimarySelectionOfferV1Handlers) Dispatcher() ZwpPrimarySelectionOfferV1Dispatcher {
	return ZwpPrimarySelectionOfferV1Dispatcher{func(opcode uint32, a *argSlots) {
		switch opcode {
		case 0:
			if h.Offer != nil {
				h.Offer(goString(a[0]))
			}
		}
	}}
}
