// Code generated by wlgen from text_input_unstable_v3.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// ZwpTextInputV3 is zwp_text_input_v3: text input.
type ZwpTextInputV3 struct{ Proxy }

// ZwpTextInputV3Interface is the wl_interface table for zwp_text_input_v3.
var ZwpTextInputV3Interface Interface

// ZwpTextInputV3.change_cause enum.
const (
	// input method caused the change
	ZwpTextInputV3ChangeCauseInputMethod = 0
	// something else than the input method caused the change
	ZwpTextInputV3ChangeCauseOther = 1
)

// ZwpTextInputV3.content_hint enum.
const (
	// no special behavior
	ZwpTextInputV3ContentHintNone = 0x0
	// suggest word completions
	ZwpTextInputV3ContentHintCompletion = 0x1
	// suggest word corrections
	ZwpTextInputV3ContentHintSpellcheck = 0x2
	// switch to uppercase letters at the start of a sentence
	ZwpTextInputV3ContentHintAutoCapitalization = 0x4
	// prefer lowercase letters
	ZwpTextInputV3ContentHintLowercase = 0x8
	// prefer uppercase letters
	ZwpTextInputV3ContentHintUppercase = 0x10
	// prefer casing for titles and headings (can be language dependent)
	ZwpTextInputV3ContentHintTitlecase = 0x20
	// characters should be hidden
	ZwpTextInputV3ContentHintHiddenText = 0x40
	// typed text should not be stored
	ZwpTextInputV3ContentHintSensitiveData = 0x80
	// just Latin characters should be entered
	ZwpTextInputV3ContentHintLatin = 0x100
	// the text input is multiline
	ZwpTextInputV3ContentHintMultiline = 0x200
)

// ZwpTextInputV3.content_purpose enum.
const (
	// default input, allowing all characters
	ZwpTextInputV3ContentPurposeNormal = 0
	// allow only alphabetic characters
	ZwpTextInputV3ContentPurposeAlpha = 1
	// allow only digits
	ZwpTextInputV3ContentPurposeDigits = 2
	// input a number (including decimal separator and sign)
	ZwpTextInputV3ContentPurposeNumber = 3
	// input a phone number
	ZwpTextInputV3ContentPurposePhone = 4
	// input an URL
	ZwpTextInputV3ContentPurposeUrl = 5
	// input an email address
	ZwpTextInputV3ContentPurposeEmail = 6
	// input a name of a person
	ZwpTextInputV3ContentPurposeName = 7
	// input a password (combine with sensitive_data hint)
	ZwpTextInputV3ContentPurposePassword = 8
	// input is a numeric password (combine with sensitive_data hint)
	ZwpTextInputV3ContentPurposePin = 9
	// input a date
	ZwpTextInputV3ContentPurposeDate = 10
	// input a time
	ZwpTextInputV3ContentPurposeTime = 11
	// input a date and time
	ZwpTextInputV3ContentPurposeDatetime = 12
	// input for a terminal
	ZwpTextInputV3ContentPurposeTerminal = 13
)

// Destroy sends zwp_text_input_v3.destroy: Destroy the wp_text_input.
// It destroys the proxy; do not use it afterwards.
func (px ZwpTextInputV3) Destroy() {
	px.marshal(0, nil, 0, marshalFlagDestroy)
}

// Enable sends zwp_text_input_v3.enable: Request text input to be enabled.
func (px ZwpTextInputV3) Enable() {
	px.marshal(1, nil, 0, 0)
}

// Disable sends zwp_text_input_v3.disable: Disable text input on a surface.
func (px ZwpTextInputV3) Disable() {
	px.marshal(2, nil, 0, 0)
}

// SetSurroundingText sends zwp_text_input_v3.set_surrounding_text: sets the surrounding text.
func (px ZwpTextInputV3) SetSurroundingText(text string, cursor int32, anchor int32) {
	textC := cString(text, false)
	px.marshal(3, nil, 0, 0, cStringPtr(textC), uintptr(uint32(cursor)), uintptr(uint32(anchor)))
	runtime.KeepAlive(textC)
}

// SetTextChangeCause sends zwp_text_input_v3.set_text_change_cause: indicates the cause of surrounding text change.
func (px ZwpTextInputV3) SetTextChangeCause(cause uint32) {
	px.marshal(4, nil, 0, 0, uintptr(cause))
}

// SetContentType sends zwp_text_input_v3.set_content_type: set content purpose and hint.
func (px ZwpTextInputV3) SetContentType(hint uint32, purpose uint32) {
	px.marshal(5, nil, 0, 0, uintptr(hint), uintptr(purpose))
}

// SetCursorRectangle sends zwp_text_input_v3.set_cursor_rectangle: set cursor position.
func (px ZwpTextInputV3) SetCursorRectangle(x int32, y int32, width int32, height int32) {
	px.marshal(6, nil, 0, 0, uintptr(uint32(x)), uintptr(uint32(y)), uintptr(uint32(width)), uintptr(uint32(height)))
}

// Commit sends zwp_text_input_v3.commit: commit state.
func (px ZwpTextInputV3) Commit() {
	px.marshal(7, nil, 0, 0)
}

// ZwpTextInputV3Handlers holds one func per zwp_text_input_v3 event. A nil func ignores the event.
// Strings and arrays are only valid until the func returns.
type ZwpTextInputV3Handlers struct {
	// Enter is zwp_text_input_v3.enter: enter event.
	Enter func(surface Surface)
	// Leave is zwp_text_input_v3.leave: leave event.
	Leave func(surface Surface)
	// PreeditString is zwp_text_input_v3.preedit_string: pre-edit.
	PreeditString func(text string, cursorBegin int32, cursorEnd int32)
	// CommitString is zwp_text_input_v3.commit_string: text commit.
	CommitString func(text string)
	// DeleteSurroundingText is zwp_text_input_v3.delete_surrounding_text: delete surrounding text.
	DeleteSurroundingText func(beforeLength uint32, afterLength uint32)
	// Done is zwp_text_input_v3.done: apply changes.
	Done func(serial uint32)
}

// SetHandlers routes the events of px to h, replacing any earlier handlers.
func (px ZwpTextInputV3) SetHandlers(h ZwpTextInputV3Handlers) { px.SetDispatcher(h.Dispatcher()) }

// ZwpTextInputV3Dispatcher is the decoder for ZwpTextInputV3Handlers, built once by Dispatcher
// and installed on any number of proxies without allocating.
type ZwpTextInputV3Dispatcher struct {
	f func(opcode uint32, a *argSlots)
}

// SetDispatcher routes the events of px to d, replacing any earlier handlers.
func (px ZwpTextInputV3) SetDispatcher(d ZwpTextInputV3Dispatcher) { px.setDispatch(d.f) }

// Dispatcher builds the event decoder for h.
func (h ZwpTextInputV3Handlers) Dispatcher() ZwpTextInputV3Dispatcher {
	return ZwpTextInputV3Dispatcher{func(opcode uint32, a *argSlots) {
		switch opcode {
		case 0:
			if h.Enter != nil {
				h.Enter(Surface{Proxy{ptr: a[0]}})
			}
		case 1:
			if h.Leave != nil {
				h.Leave(Surface{Proxy{ptr: a[0]}})
			}
		case 2:
			if h.PreeditString != nil {
				h.PreeditString(goString(a[0]), int32(uint32(a[1])), int32(uint32(a[2])))
			}
		case 3:
			if h.CommitString != nil {
				h.CommitString(goString(a[0]))
			}
		case 4:
			if h.DeleteSurroundingText != nil {
				h.DeleteSurroundingText(uint32(a[0]), uint32(a[1]))
			}
		case 5:
			if h.Done != nil {
				h.Done(uint32(a[0]))
			}
		}
	}}
}
