// Code generated by wlgen from input_method_unstable_v2.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// ZwpInputPopupSurfaceV2 is zwp_input_popup_surface_v2: popup surface.
type ZwpInputPopupSurfaceV2 struct{ Proxy }

// ZwpInputPopupSurfaceV2Interface is the wl_interface table for zwp_input_popup_surface_v2.
var ZwpInputPopupSurfaceV2Interface Interface

// Destroy sends zwp_input_popup_surface_v2.destroy.
// It destroys the proxy; do not use it afterwards.
func (px ZwpInputPopupSurfaceV2) Destroy() {
	px.marshal(0, nil, 0, marshalFlagDestroy)
}

// ZwpInputPopupSurfaceV2Handlers holds one func per zwp_input_popup_surface_v2 event. A nil func ignores the event.
// Strings and arrays are only valid until the func returns.
type ZwpInputPopupSurfaceV2Handlers struct {
	// TextInputRectangle is zwp_input_popup_surface_v2.text_input_rectangle: set text input area position.
	TextInputRectangle func(x int32, y int32, width int32, height int32)
}

// SetHandlers routes the events of px to h, replacing any earlier handlers.
func (px ZwpInputPopupSurfaceV2) SetHandlers(h ZwpInputPopupSurfaceV2Handlers) {
	px.SetDispatcher(h.Dispatcher())
}

// ZwpInputPopupSurfaceV2Dispatcher is the decoder for ZwpInputPopupSurfaceV2Handlers, built once by Dispatcher
// and installed on any number of proxies without allocating.
type ZwpInputPopupSurfaceV2Dispatcher struct {
	f func(opcode uint32, a *argSlots)
}

// SetDispatcher routes the events of px to d, replacing any earlier handlers.
func (px ZwpInputPopupSurfaceV2) SetDispatcher(d ZwpInputPopupSurfaceV2Dispatcher) {
	px.setDispatch(d.f)
}

// Dispatcher builds the event decoder for h.
func (h ZwpInputPopupSurfaceV2Handlers) Dispatcher() ZwpInputPopupSurfaceV2Dispatcher {
	return ZwpInputPopupSurfaceV2Dispatcher{func(opcode uint32, a *argSlots) {
		switch opcode {
		case 0:
			if h.TextInputRectangle != nil {
				h.TextInputRectangle(int32(uint32(a[0])), int32(uint32(a[1])), int32(uint32(a[2])), int32(uint32(a[3])))
			}
		}
	}}
}
