// Code generated by wlgen from text_input_unstable_v3.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// ZwpTextInputManagerV3 is zwp_text_input_manager_v3: text input manager.
type ZwpTextInputManagerV3 struct{ Proxy }

// ZwpTextInputManagerV3Interface is the wl_interface table for zwp_text_input_manager_v3.
var ZwpTextInputManagerV3Interface Interface

// Destroy sends zwp_text_input_manager_v3.destroy: Destroy the wp_text_input_manager.
// It destroys the proxy; do not use it afterwards.
func (px ZwpTextInputManagerV3) Destroy() {
	px.marshal(0, nil, 0, marshalFlagDestroy)
}

// GetTextInput sends zwp_text_input_manager_v3.get_text_input: create a new text input object.
func (px ZwpTextInputManagerV3) GetTextInput(seat Seat) ZwpTextInputV3 {
	ver := px.Version()
	r := px.marshal(1, &ZwpTextInputV3Interface, ver, 0, 0, seat.ptr)
	return ZwpTextInputV3{Proxy{ptr: r, ver: ver}}
}
