// Code generated by wlgen from input_method_unstable_v2.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// ZwpInputMethodKeyboardGrabV2 is zwp_input_method_keyboard_grab_v2: keyboard grab.
type ZwpInputMethodKeyboardGrabV2 struct{ Proxy }

// ZwpInputMethodKeyboardGrabV2Interface is the wl_interface table for zwp_input_method_keyboard_grab_v2.
var ZwpInputMethodKeyboardGrabV2Interface Interface

// Release sends zwp_input_method_keyboard_grab_v2.release: release the grab object.
// It destroys the proxy; do not use it afterwards.
func (px ZwpInputMethodKeyboardGrabV2) Release() {
	px.marshal(0, nil, 0, marshalFlagDestroy)
}

// ZwpInputMethodKeyboardGrabV2Handlers holds one func per zwp_input_method_keyboard_grab_v2 event. A nil func ignores the event.
// Strings and arrays are only valid until the func returns.
type ZwpInputMethodKeyboardGrabV2Handlers struct {
	// Keymap is zwp_input_method_keyboard_grab_v2.keymap: keyboard mapping.
	Keymap func(format uint32, fd int, size uint32)
	// Key is zwp_input_method_keyboard_grab_v2.key: key event.
	Key func(serial uint32, time uint32, key uint32, state uint32)
	// Modifiers is zwp_input_method_keyboard_grab_v2.modifiers: modifier and group state.
	Modifiers func(serial uint32, modsDepressed uint32, modsLatched uint32, modsLocked uint32, group uint32)
	// RepeatInfo is zwp_input_method_keyboard_grab_v2.repeat_info: repeat rate and delay.
	RepeatInfo func(rate int32, delay int32)
}

// SetHandlers routes the events of px to h, replacing any earlier handlers.
func (px ZwpInputMethodKeyboardGrabV2) SetHandlers(h ZwpInputMethodKeyboardGrabV2Handlers) {
	px.SetDispatcher(h.Dispatcher())
}

// ZwpInputMethodKeyboardGrabV2Dispatcher is the decoder for ZwpInputMethodKeyboardGrabV2Handlers, built once by Dispatcher
// and installed on any number of proxies without allocating.
type ZwpInputMethodKeyboardGrabV2Dispatcher struct {
	f func(opcode uint32, a *argSlots)
}

// SetDispatcher routes the events of px to d, replacing any earlier handlers.
func (px ZwpInputMethodKeyboardGrabV2) SetDispatcher(d ZwpInputMethodKeyboardGrabV2Dispatcher) {
	px.setDispatch(d.f)
}

// Dispatcher builds the event decoder for h.
func (h ZwpInputMethodKeyboardGrabV2Handlers) Dispatcher() ZwpInputMethodKeyboardGrabV2Dispatcher {
	return ZwpInputMethodKeyboardGrabV2Dispatcher{func(opcode uint32, a *argSlots) {
		switch opcode {
		case 0:
			if h.Keymap != nil {
				h.Keymap(uint32(a[0]), int(int32(uint32(a[1]))), uint32(a[2]))
			}
		case 1:
			if h.Key != nil {
				h.Key(uint32(a[0]), uint32(a[1]), uint32(a[2]), uint32(a[3]))
			}
		case 2:
			if h.Modifiers != nil {
				h.Modifiers(uint32(a[0]), uint32(a[1]), uint32(a[2]), uint32(a[3]), uint32(a[4]))
			}
		case 3:
			if h.RepeatInfo != nil {
				h.RepeatInfo(int32(uint32(a[0])), int32(uint32(a[1])))
			}
		}
	}}
}
