// Code generated by wlgen from input_method_unstable_v2.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// ZwpInputMethodV2 is zwp_input_method_v2: input method.
type ZwpInputMethodV2 struct{ Proxy }

// ZwpInputMethodV2Interface is the wl_interface table for zwp_input_method_v2.
var ZwpInputMethodV2Interface Interface

// ZwpInputMethodV2.error enum.
const (
	// wl_surface has another role
	ZwpInputMethodV2ErrorRole = 0
)

// CommitString sends zwp_input_method_v2.commit_string: commit string.
func (px ZwpInputMethodV2) CommitString(text string) {
	textC := cString(text, false)
	px.marshal(0, nil, 0, 0, cStringPtr(textC))
	runtime.KeepAlive(textC)
}

// SetPreeditString sends zwp_input_method_v2.set_preedit_string: pre-edit string.
func (px ZwpInputMethodV2) SetPreeditString(text string, cursorBegin int32, cursorEnd int32) {
	textC := cString(text, false)
	px.marshal(1, nil, 0, 0, cStringPtr(textC), uintptr(uint32(cursorBegin)), uintptr(uint32(cursorEnd)))
	runtime.KeepAlive(textC)
}

// DeleteSurroundingText sends zwp_input_method_v2.delete_surrounding_text: delete text.
func (px ZwpInputMethodV2) DeleteSurroundingText(beforeLength uint32, afterLength uint32) {
	px.marshal(2, nil, 0, 0, uintptr(beforeLength), uintptr(afterLength))
}

// Commit sends zwp_input_method_v2.commit: apply state.
func (px ZwpInputMethodV2) Commit(serial uint32) {
	px.marshal(3, nil, 0, 0, uintptr(serial))
}

// GetInputPopupSurface sends zwp_input_method_v2.get_input_popup_surface: create popup surface.
func (px ZwpInputMethodV2) GetInputPopupSurface(surface Surface) ZwpInputPopupSurfaceV2 {
	ver := px.Version()
	r := px.marshal(4, &ZwpInputPopupSurfaceV2Interface, ver, 0, 0, surface.ptr)
	return ZwpInputPopupSurfaceV2{Proxy{ptr: r, ver: ver}}
}

// GrabKeyboard sends zwp_input_method_v2.grab_keyboard: grab hardware keyboard.
func (px ZwpInputMethodV2) GrabKeyboard() ZwpInputMethodKeyboardGrabV2 {
	ver := px.Version()
	r := px.marshal(5, &ZwpInputMethodKeyboardGrabV2Interface, ver, 0, 0)
	return ZwpInputMethodKeyboardGrabV2{Proxy{ptr: r, ver: ver}}
}

// Destroy sends zwp_input_method_v2.destroy: destroy the text input.
// It destroys the proxy; do not use it afterwards.
func (px ZwpInputMethodV2) Destroy() {
	px.marshal(6, nil, 0, marshalFlagDestroy)
}

// ZwpInputMethodV2Handlers holds one func per zwp_input_method_v2 event. A nil func ignores the event.
// Strings and arrays are only valid until the func returns.
type ZwpInputMethodV2Handlers struct {
	// Activate is zwp_input_method_v2.activate: input method has been requested.
	Activate func()
	// Deactivate is zwp_input_method_v2.deactivate: deactivate event.
	Deactivate func()
	// SurroundingText is zwp_input_method_v2.surrounding_text: surrounding text event.
	SurroundingText func(text string, cursor uint32, anchor uint32)
	// TextChangeCause is zwp_input_method_v2.text_change_cause: indicates the cause of surrounding text change.
	TextChangeCause func(cause uint32)
	// ContentType is zwp_input_method_v2.content_type: content purpose and hint.
	ContentType func(hint uint32, purpose uint32)
	// Done is zwp_input_method_v2.done: apply state.
	Done func()
	// Unavailable is zwp_input_method_v2.unavailable: input method unavailable.
	Unavailable func()
}

// SetHandlers routes the events of px to h, replacing any earlier handlers.
func (px ZwpInputMethodV2) SetHandlers(h ZwpInputMethodV2Handlers) { px.SetDispatcher(h.Dispatcher()) }

// ZwpInputMethodV2Dispatcher is the decoder for ZwpInputMethodV2Handlers, built once by Dispatcher
// and installed on any number of proxies without allocating.
type ZwpInputMethodV2Dispatcher struct {
	f func(opcode uint32, a *argSlots)
}

// SetDispatcher routes the events of px to d, replacing any earlier handlers.
func (px ZwpInputMethodV2) SetDispatcher(d ZwpInputMethodV2Dispatcher) { px.setDispatch(d.f) }

// Dispatcher builds the event decoder for h.
func (h ZwpInputMethodV2Handlers) Dispatcher() ZwpInputMethodV2Dispatcher {
	return ZwpInputMethodV2Dispatcher{func(opcode uint32, a *argSlots) {
		switch opcode {
		case 0:
			if h.Activate != nil {
				h.Activate()
			}
		case 1:
			if h.Deactivate != nil {
				h.Deactivate()
			}
		case 2:
			if h.SurroundingText != nil {
				h.SurroundingText(goString(a[0]), uint32(a[1]), uint32(a[2]))
			}
		case 3:
			if h.TextChangeCause != nil {
				h.TextChangeCause(uint32(a[0]))
			}
		case 4:
			if h.ContentType != nil {
				h.ContentType(uint32(a[0]), uint32(a[1]))
			}
		case 5:
			if h.Done != nil {
				h.Done()
			}
		case 6:
			if h.Unavailable != nil {
				h.Unavailable()
			}
		}
	}}
}
