// Code generated by wlgen from input_method_unstable_v2.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// ZwpInputMethodManagerV2 is zwp_input_method_manager_v2: input method manager.
type ZwpInputMethodManagerV2 struct{ Proxy }

// ZwpInputMethodManagerV2Interface is the wl_interface table for zwp_input_method_manager_v2.
var ZwpInputMethodManagerV2Interface Interface

// GetInputMethod sends zwp_input_method_manager_v2.get_input_method: request an input method object.
func (px ZwpInputMethodManagerV2) GetInputMethod(seat Seat) ZwpInputMethodV2 {
	ver := px.Version()
	r := px.marshal(0, &ZwpInputMethodV2Interface, ver, 0, seat.ptr, 0)
	return ZwpInputMethodV2{Proxy{ptr: r, ver: ver}}
}

// Destroy sends zwp_input_method_manager_v2.destroy: destroy the input method manager.
// It destroys the proxy; do not use it afterwards.
func (px ZwpInputMethodManagerV2) Destroy() {
	px.marshal(1, nil, 0, marshalFlagDestroy)
}
