// Code generated by wlgen from xdg_decoration_unstable_v1.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// ZxdgDecorationManagerV1 is zxdg_decoration_manager_v1: window decoration manager.
type ZxdgDecorationManagerV1 struct{ Proxy }

// ZxdgDecorationManagerV1Interface is the wl_interface table for zxdg_decoration_manager_v1.
var ZxdgDecorationManagerV1Interface Interface

// Destroy sends zxdg_decoration_manager_v1.destroy: destroy the decoration manager object.
// It destroys the proxy; do not use it afterwards.
func (px ZxdgDecorationManagerV1) Destroy() {
	px.marshal(0, nil, 0, marshalFlagDestroy)
}

// GetToplevelDecoration sends zxdg_decoration_manager_v1.get_toplevel_decoration: create a new toplevel decoration object.
func (px ZxdgDecorationManagerV1) GetToplevelDecoration(toplevel XdgToplevel) ZxdgToplevelDecorationV1 {
	ver := px.Version()
	r := px.marshal(1, &ZxdgToplevelDecorationV1Interface, ver, 0, 0, toplevel.ptr)
	return ZxdgToplevelDecorationV1{Proxy{ptr: r, ver: ver}}
}
