// Code generated by wlgen from xdg_decoration_unstable_v1.xml. DO NOT EDIT.

//go:build linux && !android && (amd64 || arm64)

package wl

import (
	"runtime"
	"unsafe"
)

var (
	_ = runtime.KeepAlive
	_ unsafe.Pointer
)

// ZxdgToplevelDecorationV1 is zxdg_toplevel_decoration_v1: decoration object for a toplevel surface.
type ZxdgToplevelDecorationV1 struct{ Proxy }

// ZxdgToplevelDecorationV1Interface is the wl_interface table for zxdg_toplevel_decoration_v1.
var ZxdgToplevelDecorationV1Interface Interface

// ZxdgToplevelDecorationV1.error enum.
const (
	// xdg_toplevel has a buffer attached before configure
	ZxdgToplevelDecorationV1ErrorUnconfiguredBuffer = 0
	// xdg_toplevel already has a decoration object
	ZxdgToplevelDecorationV1ErrorAlreadyConstructed = 1
	// xdg_toplevel destroyed before the decoration object
	ZxdgToplevelDecorationV1ErrorOrphaned = 2
	// invalid mode
	ZxdgToplevelDecorationV1ErrorInvalidMode = 3
)

// ZxdgToplevelDecorationV1.mode enum.
const (
	// no server-side window decoration
	ZxdgToplevelDecorationV1ModeClientSide = 1
	// server-side window decoration
	ZxdgToplevelDecorationV1ModeServerSide = 2
)

// Destroy sends zxdg_toplevel_decoration_v1.destroy: destroy the decoration object.
// It destroys the proxy; do not use it afterwards.
func (px ZxdgToplevelDecorationV1) Destroy() {
	px.marshal(0, nil, 0, marshalFlagDestroy)
}

// SetMode sends zxdg_toplevel_decoration_v1.set_mode: set the decoration mode.
func (px ZxdgToplevelDecorationV1) SetMode(mode uint32) {
	px.marshal(1, nil, 0, 0, uintptr(mode))
}

// UnsetMode sends zxdg_toplevel_decoration_v1.unset_mode: unset the decoration mode.
func (px ZxdgToplevelDecorationV1) UnsetMode() {
	px.marshal(2, nil, 0, 0)
}

// ZxdgToplevelDecorationV1Handlers holds one func per zxdg_toplevel_decoration_v1 event. A nil func ignores the event.
// Strings and arrays are only valid until the func returns.
type ZxdgToplevelDecorationV1Handlers struct {
	// Configure is zxdg_toplevel_decoration_v1.configure: notify a decoration mode change.
	Configure func(mode uint32)
}

// SetHandlers routes the events of px to h, replacing any earlier handlers.
func (px ZxdgToplevelDecorationV1) SetHandlers(h ZxdgToplevelDecorationV1Handlers) {
	px.SetDispatcher(h.Dispatcher())
}

// ZxdgToplevelDecorationV1Dispatcher is the decoder for ZxdgToplevelDecorationV1Handlers, built once by Dispatcher
// and installed on any number of proxies without allocating.
type ZxdgToplevelDecorationV1Dispatcher struct {
	f func(opcode uint32, a *argSlots)
}

// SetDispatcher routes the events of px to d, replacing any earlier handlers.
func (px ZxdgToplevelDecorationV1) SetDispatcher(d ZxdgToplevelDecorationV1Dispatcher) {
	px.setDispatch(d.f)
}

// Dispatcher builds the event decoder for h.
func (h ZxdgToplevelDecorationV1Handlers) Dispatcher() ZxdgToplevelDecorationV1Dispatcher {
	return ZxdgToplevelDecorationV1Dispatcher{func(opcode uint32, a *argSlots) {
		switch opcode {
		case 0:
			if h.Configure != nil {
				h.Configure(uint32(a[0]))
			}
		}
	}}
}
